### ISSUE TITLE
mzML write support?

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#101]
I was wondering if there are plans to add mzML write support to `mzR` - that would be really great.

**Comment by lgatto** [comment]
There were plans in the original GSoC project, but @thirdwing never got that far.

**Comment by jotsetung** [comment]
Just a notice: I'm presently looking into this.

**Comment by jotsetung** [comment]
Update:
So far I managed to write spectrum data using the `pwiz` module. In detail, I have 2 functions ready:
+ `writeSpectrumList` takes the parameters `filename`, `format`, `header` and `data` and saves this as an e.g. *mzML* file. `header` has to be in the format as returned by the `mzR::header` method and `data` in the format as returned by `mzR::peaks`. Purpose is to write a simple *mzML* file without much additional information about settings, processing etc.
+ `copyWriteMSfile` with the same parameters and the additional `originalFile` parameter. This function copies the general information from the original (mzML) file (i.e. data processings, instrument settings etc) and replaces its spectrum data with the new data. The idea behind this method was to enable some sort of *serialization* of an `OnDiskMSnExp` or `MSnExp` object after e.g. a computationally intense operation was carried out. Use case for me is that I want to do the peak picking on the raw profile mode data in R/MSnbase and after that I would like to save this centroided data before actually performing the chromatographic peak detection.

I was also thinking over implementing or rather wrapping the `pwiz::MSData` C++ object into R, but came to the conclusion that that might be an overkill. I am currently in favor of the above described relatively light-weighted and simple approach to have some simple functions to do the job.

Open for discussions @sneumann and @lgatto

**Comment by lgatto** [comment]
I am generally fine with the above, as long as the files are valid at the end - I think there's a file validator in pwiz.

Regarding `copyWriteMSfile`,  one issue I see is that the data processing information in that raw file won't be correct any more after some additional processing.

**Comment by jotsetung** [comment]
> Regarding `copyWriteMSfile`, one issue I see is that the data processing information in that raw file won't be correct any more after some additional processing.

I think this should be OK as long as we add also the additional processing steps. I'm playing around a little with this at the moment to see what would be the best way to pass this information. Basically we can add 1) software (+version) to the mzML file and 2) data processing steps (linking to the software) and providing also their order.

We can discuss this also at CSAMA2017

**Comment by jotsetung** [comment]
Done with the merge of https://github.com/sneumann/mzR/pull/111
