### ISSUE TITLE
warning: "BOOST_HAS_WINTHREADS" redefined  #  define BOOST_HAS_WINTHREADS

### ISSUE THREAD

**Issue by tsufz** [sneumann/mzR#102]
Windows complains:

```
./boost/config/platform/win32.hpp:61:0: warning: "BOOST_HAS_WINTHREADS" redefined
 #  define BOOST_HAS_WINTHREADS
```

**Comment by lgatto** [comment]
Please provide more details, otherwise we won't be able to help.

**Comment by sneumann** [comment]
This is a warning that is probably harmless but that clobbers the compiler output:
http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/tokay2-install.html
