### ISSUE TITLE
version missmatch between Bioconductor svn and homepage

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#104]
On the Bioconductor homepage the version listed for `mzR` is 2.11.0 (http://bioconductor.org/packages/devel/bioc/html/mzR.html), but the version in the Bioc SVN is 2.9.12. 
Problem is that the version 2.9.12 uses the `pwiz` backend by default, while the version 2.11.0 (presumably older than 2.9.12) does not. Could be that I messed this up with my pull request as I eventually bumped the wrong version, or that I made the pull request to the wrong branch?

**Comment by lgatto** [comment]
Yes, there was a mess-up in version numbers. I am about to fix the devel version to 2.11.1, which included the backend change. Are we missing anything else?

**Comment by lgatto** [comment]
Done now on svn. Homepage should update after the next (successful) build.
