### ISSUE TITLE
Is precursorScanNum linked to acquisitionNum or seqNum?

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#105]
@lgatto, eventually you known this: is the `"precursorScanNum"` reported by the `mzR::header` method linked to the `acquisitionNum` or the `seqNum` column of the same `data.frame`?

**Comment by jotsetung** [comment]
To explain a little more: I'm testing some code to write mzML files (issue #101) based on a `data.frame` in the format returned by the `mzR::header` method and a `list` with content same as returned by `mzR::peaks`. When it gets to write MSn data it gets tricky with what id to provide as the `precursor.spectrumID`.
As spectrum ID I am using a string that combines `"scan="` with the `acquisitionNum`. So I'm about to use `"scan="` concatenated with `precursorScanNum[i]` for the precursor scan ID. I guess that should be correct - as long as the number reported in column `"precursorScanNum"` does not relate to the number of the scan observed in the file (i.e. the `"seqNum"`).

**Comment by lgatto** [comment]
I think this has now been addressed, since the new `spectrumID` variable in the header. If so, @jotsetung, could you close?

**Comment by jotsetung** [comment]
Yup, will do. To clarify: precursorScanNum links in fact to the acquisition number of the precursor spectrum.

**Comment by lgatto** [comment]
Wouldn't it make sense to explain all these details in the man page, ad similar questions come up regularly. 

Maybe also in `MSnbase` somewhere in relation to how identification data is matched with the raw data.

Cc @sgibb

**Comment by jotsetung** [comment]
I'll add it in the mzR man page.
