### ISSUE TITLE
getInstrumentInfo() fails for Waters xevo tof g-2xs

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#113]
Hi, @nsadawi reported that mzR fails to read 

```
> mzmlfile <- 'testfile.mzML'
> ms <- openMSfile(mzmlfile)
> mzR:::instrumentInfo(ms)
Error in object@backend$getInstrumentInfo() : 
  [ComponentList::detector] Detector 0 is out of range; only found 0 detectors
```
with traceback:
```
> traceback()
5: stop(list(message = "[ComponentList::detector] Detector 0 is out of range; only found 0 detectors", 
       call = object@backend$getInstrumentInfo(), cppstack = NULL))
4: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x55b2afdc5eb0>, 
       dll = list(name = "Rcpp", path = "/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so", 
           dynamicLookup = TRUE, handle = <pointer: 0x55b2afe3ee40>, 
           info = <pointer: 0x7fcd83e69e00>), numParameters = -1L), 
       <pointer: 0x55b2afec78f0>, <pointer: 0x55b2b1035770>, .pointer)
3: object@backend$getInstrumentInfo()
2: mzR:::instrumentInfo(ms)
1: mzR:::instrumentInfo(ms)
```

The error is thrown in 
https://github.com/sneumann/mzR/blob/master/src/pwiz/data/msdata/MSData.cpp#L165

The file was converted with `<software id="pwiz_Reader_Waters" version="3.0.10998">` 
and shows this instrumentConfiguration:
```
    <instrumentConfigurationList count="1">
      <instrumentConfiguration id="IC">
        <cvParam cvRef="MS" accession="MS:1000126" name="Waters instrument model" value=""/>
      </instrumentConfiguration>
    </instrumentConfigurationList>
```
Yours, Steffen

**Comment by sneumann** [comment]
`msconvert testfile.mzML --mzXML -o /tmp` works fine.
`mscat testfile.mzML | wc -l` works fine.
OpenMS reports:
```docker run -v $PWD:/tmp hroest/openms-executables-2.1 FileInfo -in /tmp/testfile.mzML
While loading '/tmp/testfile.mzML': Ill formed absolute or relative sourceFile path: file://C:\Users\XXX\Desktop\testfile.raw
Progress of 'loading spectra list':
-- done [took 22.59 s (CPU), 23.28 s (Wall)] -- 
Progress of 'loading chromatogram list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 


Mem Usage while loading: 1458 MB

-- General information --

File name: /tmp/testfile.mzML
File type: mzML

Peak type (metadata): Unknown
Peak type (estimated): Raw data
Estimated raw data spacing: 0.203857 (min: 0.00424194, max: 7.97804)

Number of spectra: 3765
Number of peaks: 88816590

Ranges:
  retention time: 1.27 .. 878.85
  mass-to-charge: 49.99 .. 2000.10
  intensity:      14.08 .. 39522656.00

MS levels: 1
Number of spectra per MS level:
  level 1: 3765

Number of chromatograms: 1
Number of chromatographic peaks: 3765

Number of chromatograms per type: 
  total ion current chromatogram:                         1


FileInfo took 26.37 s (wall), 24.28 s (CPU), 0.00 s (system), 24.28 s (user).
<While loading '/tmp/testfile.mzML': Ill formed absolute or relative sourceFile path: file://C:\Users\XXX\Desktop\testfile.raw> occurred 14 times
```

**Comment by jaketmp** [comment]
As an additional datapoint, we see the same error running Xevo G2-S and Synapt G2-S data through the same pipeline. Happy to provide example datafiles if needed.

**Comment by sneumann** [comment]
A bit more diagnostics:
While the presence of `<detector>` is mandatory inside a `<componentList>` according to http://www.peptideatlas.org/tmp/mzML1.1.0.html#componentList,
the presence of the `<componentList>` itself inside `<instrumentConfiguration>` is not mandatory (http://www.peptideatlas.org/tmp/mzML1.1.0.html#instrumentConfiguration).

mzR is is calling the LegacyAdapter_Instrument in 
https://github.com/sneumann/mzR/blob/bdfa3b26352ad88df89e73705dd8acb3111d3e89/src/RcppPwiz.cpp#L113
implemented by pwiz in https://github.com/sneumann/mzR/blob/master/src/pwiz/data/msdata/LegacyAdapter.cpp#L231
which seems (my C++ is a bit rusty) to assume a `<detector>` is always present in an `<instrumentConfiguration>`

**Comment by sneumann** [comment]
Small file to reproduce, this is the file MM14.mzML from http://bioconductor.org/packages/release/data/experiment/html/msdata.html with the `<componentList>` removed manually in an editor.
```
> library(mzR)
Loading required package: Rcpp
> ms <- openMSfile("/tmp/MM14-withoutComponentList.mzML")
> instrumentInfo(ms)
Error in object@backend$getInstrumentInfo() : 
  [ComponentList::detector] Detector 0 is out of range; only found 0 detectors
```
[MM14-withoutComponentList.zip](https://github.com/sneumann/mzR/files/1193221/MM14-withoutComponentList.zip)

**Comment by lgatto** [comment]
This is with the `pwiz` backend, right?

**Comment by sneumann** [comment]
Yes, thats pwiz. Yours Steffen

---
I blame Android for the brevity and typos

**Comment by nsadawi** [comment]
Same here, it's all xcms backend
Regs, Noureddin

**Comment by jotsetung** [comment]
I'll have a look at it. In worst case we could make a `try-catch` around.

**Comment by lgatto** [comment]
Merged into master and pushed to Bioc devel.

**Comment by jotsetung** [comment]
Just a question, are you now pushing to Bioc git or still svn?

**Comment by jotsetung** [comment]
OK, thanks!

**Comment by nsadawi** [comment]
This is to confirm it now works nicely
For the general benefit, I'm using a MacBook Air
I needed to install `netcdf` via `macports`
and then `install_github("sneumann/mzR",force = TRUE)`
I also installed `RNetCDF`

Many thanks,
Noureddin

**Comment by sneumann** [comment]
Brian Pratt added a fix to the pwiz code, see
https://sourceforge.net/p/proteowizard/code/11174/tree//trunk/pwiz/pwiz/data/msdata/LegacyAdapter.cpp?diff=50de01fe34309d7d5acfb788:11173

**Comment by sneumann** [comment]
with the patch in #116 we now get 
```
> library(mzR)
Loading required package: Rcpp
> ms <- openMSfile("testfile.mzML")
> instrumentInfo(ms)
$manufacturer
[1] "instrument model"

$model
[1] "Waters instrument model"

$ionisation
[1] "Unknown"

$analyzer
[1] "Unknown"

$detector
[1] "Unknown"

$software
[1] "MassLynx 4.1"

$sample
[1] ""

$source
[1] ""
```
