### ISSUE TITLE
Proteowizard has a newer version of src/pwiz/data/common/cv.cpp that includes PeptideShaker

### ISSUE THREAD

**Issue by jj-umn** [sneumann/mzR#12]

**Comment by thirdwing** [comment]
Hi, @jj-umn ,

Can you give a little more info on this? If it is necessary, I can add it.

**Comment by lgatto** [comment]
@jj-umn - Is this only/mainly a matter of control vocabulary?

**Comment by jj-umn** [comment]
I think this is probably just an update to the controlled vocabulary.  
I was very impressed with the speed with which mzR delivered results, but one of the sample mzIdentML files I needed to access was from PeptideShaker.  That is when I discovered that pwiz failed when encountering the CV for PeptideShaker.   The Proteowizard github page has a newer version of vocabulary.

**Comment by lgatto** [comment]
Thanks for the clarification. 
@thirdwing - do you think it would be enough to update `cv.cpp` or all files in `pwiz/data/common` rather then checking out the full code base?

**Comment by thirdwing** [comment]
I will try it this weekend.

**Comment by sneumann** [comment]
Please check the commit that changed could.cpp and look what other files where changed. Yours Steffen

**Comment by lgatto** [comment]
@thirdwing did you have time to check?

**Comment by thirdwing** [comment]
Sorry, @lgatto . Exams in following two days. I will find some time in weekend.

**Comment by lgatto** [comment]
On 14 January 2015 21:34:42 CET, "Qiang Kou (KK)" <notifications@github.com> wrote:
>Sorry, @lgatto . Exams in following two days. I will find some time in
>weekend.

No worries. Good luck for your exams!
