### ISSUE TITLE
Report the spectrum ID in the header

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#124]
This issue is related to https://github.com/sneumann/xcms/issues/216 . Basically, the mzML files can not be processed as they are and it would be nice to split/filter mzML files converted from Waters' multi-function raw data format (see referenced issue for more details).

As of now, the only way to determine which spectrum is related to which function is by its ID:
```
  <spectrum index="1" id="function=4 process=0 scan=1" defaultArrayLength="18475">
```

Currently it is not possible to filter/split such files, because the ID is not reported in the header. And that's why I suggest that we add a column `spectrumId` to the `data.frame` returned by `header`.

Note that only the `pwiz` backend does support extraction of the ID, for `ramp` and `netCDF` backends we would have to return e.g. the `acquisitionNum` as the `spectrumId`.

@sneumann @lgatto any comments?

**Comment by lgatto** [comment]
Yes, that would be a great addition to have the function, but I am a bit confused as to what you want to add. Would that be a `spectrumId` character column that contains `"function=4 process=0 scan=1"`?

I would suggest to have 3 new  feature variables, namely `function` (the one of interest), `process` and `scan`, or, if you prefer, prefix them and use `spectrumIdFunction`, `spectrumIdProcess` and `spectrumIdScan` (or similar), although I prefer the shorter forms.

**Comment by jotsetung** [comment]
I suggested to add the full id (character string) as it is written in the mzML file as a `spectrumId` column to the header `data.frame`. I would let any further processing of that to the user - the id is not always formatted in the same way, my mzML files have e.g.
```
<spectrum index="0" id="sample=1 period=1 cycle=1 experiment=1" defaultArrayLength="1625" dataProcessingRef="pwiz_Reader_ABI_conversion">
```

**Comment by lgatto** [comment]
Oh dear, so much for consistency. Ok then, a character it is :-/

**Comment by jaketmp** [comment]
The content of `id=` seems to be defined in the [psi-ms-cv](https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo) on a vendor-by-vendor basis:

```
[Term]
id: MS:1000767
name: native spectrum identifier format
def: "Describes how the native spectrum identifiers are formated." [PSI:MS]
synonym: "nativeID format" EXACT []
relationship: part_of MS:1000577 ! raw data file
```
For Waters:
```
[Term]
id: MS:1000769
name: Waters nativeID format
def: "Native format defined by function=xsd:positiveInteger process=xsd:nonNegativeInteger scan=xsd:nonNegativeInteger." [PSI:MS]
is_a: MS:1000767 ! native spectrum identifier format
```
Doesn't look like much cross vendor harmony though.

**Comment by jotsetung** [comment]
Yes, it's pretty inconsistent. proteowizard must create this ID based on some (?) criteria but I don't know which. And no idea what manufacturer's software (if they convert to mzML) would use as ID.

Also, the `mzXML` format does not seem have such an ID. So, if we're going to return a `header$spectrumId` this will only have a meaningful value for `mzML` files read with the `pwiz` format. `ramp` and `netCDF` backends do not support it and we would have to return e.g. the acquisitionNum as ID instead (or better `NA_string`) - same for `mzXML` files. Thus I wanted to discuss this first before implementing and making a pull request -

**Comment by jotsetung** [comment]
Just as an info:
Thermo has: `<spectrum index="0" id="controllerType=0 controllerNumber=1 scan=1" defaultArrayLength="10" dataProcessingRef="pwiz_Reader_Thermo_conversion">`.

Than I have a Bruker file with: `<spectrum index="0" id="scan=1" defaultArrayLength="837">`

**Comment by jaketmp** [comment]
I count 24 distinct `is_a: MS:1000767` in the PSI CV - can't see anything that attempts to map the contents of the string to a common set of terms though.

They do define a case for where no id is available for compatibility with mzXML though, that could serve where this is not defined:

```
[Term]
id: MS:1000776
name: scan number only nativeID format
def: "Native format defined by scan=xsd:nonNegativeInteger." [PSI:MS]
comment: Used for conversion from mzXML, or DTA folder where native scan numbers can be derived.
is_a: MS:1000767 ! native spectrum identifier format
```

**Comment by jotsetung** [comment]
Thanks @jaketmp . So, for all files/backends instead of `pwiz/mzML` we would return `"scan="<acquisitionNum>` as ID.

**Comment by jotsetung** [comment]
Note: I have also to check if I can actually **write** the id too with pwiz.

**Comment by jotsetung** [comment]
Reading the spectrum/scan ID was actually very helpful - I could fix now a potential problem when writing MSn data to mzML or mzXML causing a mis-match of MSn spectra with precursor spectra

**Comment by jotsetung** [comment]
Pull request is in - waiting for the review.

**Comment by lgatto** [comment]
Merged. Thank you @jotsetung!
