### ISSUE TITLE
header support for chromatograms

### ISSUE THREAD

**Issue by wilsontom** [sneumann/mzR#141]
This is more of a feature request than an issue.

Now that `mzR` supports chromatogram data such as SRM-MS; it is possible to extend some of the functionality of `header` to chromatograms. At present there is no "easy" way of retrieving parent/product masses and polarity _via_ `mzR`. 

Thanks

Tom

**Comment by lgatto** [comment]
Have you looked at [`Chromatogram`](https://lgatto.github.io/MSnbase/reference/Chromatograms-class.html) objects in `MSnbase`? Does that do what you want?

**Comment by wilsontom** [comment]
The structure of the `Chromatogram` class is ideal for representation of the chromatograms; but I was thinking of a method for populating this class directly from a `.mzML` file.  Currently the only information for chromatogram headers is stored in the names of chromatograms which requires manual parsing;

```R
xraw <- mzR::openMSfile('example_qqq.mzML')
chrom <- mzR::chromatograms(xraw)
names(chrom[[2]])

[1] "time"                      "X..SRM.SIC.169.019.79.073"
```
Polarity, parent and product mass are all contained in the  `</chromatogram>` block of the `mzML` file. Is there any way this can be accessed during `mzR::openMSfile` ?

Tom

**Comment by lgatto** [comment]
See the [`chromatogram` method](https://lgatto.github.io/MSnbase/reference/chromatogram-MSnExp-method.html), that creates (extracted ion) chromatograms one or multiple a raw data files. This is the convenient higher-level version of what you use in `mzR`.

**Comment by wilsontom** [comment]
I am unable to open the file using `MSnbase::readMSData`

```R
readMSData('example_qqq.mzML', mode = 'onDisk')

Error in object@backend$getAllScanHeaderInfo() : 
  upper value must be greater than lower value
```

**Comment by lgatto** [comment]
What's your `sessionInfo()`? Have been able to successfully run the example code? Is your test file accessible so that we can try it out?

**Comment by wilsontom** [comment]
The `MSnbase` example runs fine. `sessionInfo()` as follows;

```R
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] MSnbase_2.4.0       ProtGenerics_1.10.0 BiocParallel_1.12.0
[4] mzR_2.12.0          Rcpp_0.12.14        Biobase_2.38.0     
[7] BiocGenerics_0.24.0 msdata_0.18.0      

loaded via a namespace (and not attached):
 [1] IRanges_2.12.0        zlibbioc_1.24.0       doParallel_1.0.11    
 [4] munsell_0.4.3         colorspace_1.3-2      impute_1.52.0        
 [7] lattice_0.20-35       rlang_0.1.4           foreach_1.4.3        
[10] plyr_1.8.4            mzID_1.16.0           grid_3.4.3           
[13] gtable_0.2.0          affy_1.56.0           iterators_1.0.8      
[16] digest_0.6.12         lazyeval_0.2.1        tibble_1.3.4         
[19] preprocessCore_1.40.0 affyio_1.48.0         ggplot2_2.2.1        
[22] S4Vectors_0.16.0      codetools_0.2-15      MALDIquant_1.17      
[25] limma_3.34.2          BiocInstaller_1.28.0  compiler_3.4.3       
[28] pcaMethods_1.70.0     scales_0.5.0          stats4_3.4.3         
[31] XML_3.98-1.9          vsn_3.46.0     
```
The test file is [here]( https://github.com/wilsontom/MRMConverteR/blob/master/inst/extdata/)

**Comment by lgatto** [comment]
Yes, it fails because it is not a raw MS data file, but a file containing (extracted ion) chromatograms. I don't remember if we have a constructor for these - @jotsetung, do you know?

**Comment by jotsetung** [comment]
so far the `chromatogram` functionality (in `MSnbase`) is only to create chromatographic data from a MS file containing spectra. Reading the `chromatogram` directly from the mzML would require hacking into `mzML`. I haven't had a look at how such data could be read. I assume proteowizard supports it, so it should not be impossible but would require major changes.

**Comment by lgatto** [comment]
I was rather thinking of a `readChromData` function that creates a `Chromatograms` object.

**Comment by lgatto** [comment]
@wilsontom - I am closing this issue as it doesn't apply to `mzR` anyway. Feel free to follow up in a new `MSnbase` issue.

**Comment by lgatto** [comment]
Re-opening issue, as I conflated two things here. @wilsontom, what is the CV terms you are looking for?

**Comment by wilsontom** [comment]
precursor mass, product mass and polarity are the key things to extract.

precursor and product masses are identified in the `.mzML` file as `name="isolation window target m/z"` with `accession="MS:1000827"` in either a `<precursor>` or `<product>` block. 

Polarity is in the `<chromatogram>` block, and given as either `negative scan; accession="MS:1000129"` or `positive scan; accession="MS:1000130"`

**Comment by jotsetung** [comment]
So, it will be a `chromatogramHeader` and `chromatogram` method in `mzR` to extract chromatographic data?

**Comment by jotsetung** [comment]
OK, wasn't aware that there is a `chromatogram` method that does in fact read (all) chromatogram data. So, there is *only* reading the header left...

**Comment by jotsetung** [comment]
OK, pull request is in. @wilsontom, could you please check if that works for you. Once the code is in `mzR` I will then add functionality to `MSnbase` to read chromatographic data from a mzML (something like a `readChromatograms` function).

**Comment by wilsontom** [comment]
Apologies for the delay getting to this. Thanks very much @jotsetung. 

`chromatogramHeader` works OK; except that the polarity coding for negative and TIC are switched. 

All positive chromatograms are `1` but negative chromatograms are coded as `0` and the TIC as `-1`.

Thanks

Tom

**Comment by jotsetung** [comment]
polarity encoding is a little tricky (see also https://github.com/sneumann/mzR/issues/46). was also confused at the beginning, but positive is encoded as `+1`, negative as `0` and unknown as `-1`.

**Comment by wilsontom** [comment]
Ah, my mistake. 

I'll close the issue now, as this is all working perfectly. 

Thanks again

Tom

**Comment by jotsetung** [comment]
Note that the implementation to read and represent SRM/MRM data is on its way also in `MSnbase`.
