### ISSUE TITLE
Checks fail: mzXML export does not support writing filter string

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#145]
All plattforms: http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/malbec2-checksrc.html
```
* checking tests ...
  Running ‘runTests.R’
 ERROR
Running the tests in ‘tests/runTests.R’ failed.
Last 13 lines of output:
  2: In mzR::copyWriteMSData(file = fnew, original_file = orig_file,  :
    mzXML export does not support writing filter string
```

**Comment by lgatto** [comment]
@jotsetung - have you seen this? That is expected, isn't it, as only `mzML` write is supported?

**Comment by jotsetung** [comment]
pwiz supports `mzXML` export, so it is supported. Could be related to some recent changes in `msdata` (i.e. new files there)? I'll look into it.

**Comment by jotsetung** [comment]
Writing `mzXML` actually works - throws just warnings.

**Comment by jotsetung** [comment]
The error came actually from another unit test. I fixed that and added some more changes that would eventually have resulted in error.
