### ISSUE TITLE
Installing mzR on Alpine Docker with R 

### ISSUE THREAD

**Issue by Ru13en** [sneumann/mzR#148]
Hi,
I don't know if is some missing dependency or any other problem related with the mzR.
When i try to install mzR package on R, i have the next issue:

```
pwiz/data/msdata/BinaryDataEncoder.cpp: In member function 'void pwiz::msdata::BinaryDataEncoder::Impl::encode(const double*, size_t, std::__cxx11::string&, size_t*)':
pwiz/data/msdata/BinaryDataEncoder.cpp:258:13: error: 'mustEndianize' was not declared in this scope
         if (mustEndianize)
             ^~~~~~~~~~~~~
pwiz/data/msdata/BinaryDataEncoder.cpp: In member function 'void pwiz::msdata::BinaryDataEncoder::Impl::decode(const char*, size_t, std::vector<double>&)':
pwiz/data/msdata/BinaryDataEncoder.cpp:421:17: error: 'mustEndianize' was not declared in this scope
             if (mustEndianize)
                 ^~~~~~~~~~~~~
make: *** [/usr/lib/R/etc/Makeconf:166: pwiz/data/msdata/BinaryDataEncoder.o] Error 1
ERROR: compilation failed for package ‘mzR’
* removing ‘/usr/lib/R/library/mzR’
```

I tried using the biocLite but gives that error.
If i install mzR using the devtools:install_github , i also need to run devtools::install_github('grimbough/Rhdf5lib') to get the latest Rhdf5lib. 
However i get stuck again in the same error described above.

My docker contains several dependencies and compilers for c++, boost, etc...
If some one whats to test the issue, can use this dockerfile code:

```
From bisbii/shiny

RUN apk update upgrade

RUN apk add --no-cache --virtual=.build-dependencies \
	ca-certificates \
	make \
	cmake \
	gcc \
	g++ \
	build-base \
	linux-headers \
	R-dev \
	python \
	unzip \
	wget \
	gfortran \
	m4 \
	libstdc++ \
	zlib-dev \
	libxml2-dev \
	curl \
	openssl-dev \
	glu-dev \
	libssh2-dev \
	boost \
	boost-dev \
	mariadb-client-libs

# HDF5 Installation
RUN wget https://www.hdfgroup.org/package/bzip2/?wpdmdl=4301 \
        && mv "index.html?wpdmdl=4301" hdf5-1.10.1.tar.gz \
        && tar xf hdf5-1.10.1.tar.gz \
        && cd hdf5-1.10.1 \
        && ./configure --prefix=/usr --enable-cxx --with-zlib=/usr/include,/usr/lib/x86_64-linux-gnu \
        && make -j4 \
        && make install \
        && cd .. \
        && rm -rf hdf5-1.10.1 \
        && rm -rf hdf5-1.10.1.tar.gz \
        && export HDF5_DIR=/usr

# NetCDF Installation
RUN wget https://github.com/Unidata/netcdf-c/archive/v4.6.0.tar.gz \
	&& tar xf v4.6.0.tar.gz \
    && cd netcdf-c-4.6.0 \
    && ./configure --prefix=/usr \
    && make -j4 \
	&& make install \
	&& cd .. \
	&& rm -rf netcdf-c-4.6.0 \
	&& rm -rf v4.6.0.tar.gz

# NLopt Installation
RUN wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz \
	&& tar xf nlopt-2.4.2.tar.gz \
	&& cd nlopt-2.4.2 \
	&& ./configure --prefix=/usr --with-pic \
	&& make \
	&& make install \
	&& cd .. \
	&& rm -rf nlopt-2.4.2 \
	&& rm -rf nlopt-2.4.2.tar.gz

RUN R -e "source('https://bioconductor.org/biocLite.R');biocLite()"
# mzR Installation
RUN R -e "source('https://bioconductor.org/biocLite.R');biocLite('mzR')"
RUN apk del .build-dependencies

ENTRYPOINT ["/usr/bin/shiny-server.sh"]
```
Some one can help me solving this issue?
Thank you for your attention

**Comment by lgatto** [comment]
What `gcc` version are you using. I'm still stuck with an old ubuntu/gcc, but  there have been reports of issues with up-to-date systems.

**Comment by Ru13en** [comment]
This version:
https://pkgs.alpinelinux.org/package/v3.7/main/x86/gcc

**Comment by Ru13en** [comment]
I can say that the package runs this command:

g++ -std=gnu++11 -I/usr/include/R -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/usr/lib/R/library/Rcpp/include" -I"/usr/lib/R/library/zlibbioc/include" -Os -fomit-frame-pointer   -fpic  -Os -fomit-frame-pointer -D__MUSL__ -c pwiz/data/msdata/BinaryDataEncoder.cpp -o pwiz/data/msdata/BinaryDataEncoder.o

I even tried using the GLIBC 2.27-r0 from "https://github.com/sgerrand/alpine-pkg-glibc/releases/download without any lucky.

I think that is something related with the 
#if defined(__GLIBC__) || defined(__GLIBCXX__)
#define PWIZ_GCC
#endif

from https://github.com/sneumann/mzR/blob/39bf5d5d8c8588ca82c1fbdae28f98ded44c6a94/src/pwiz/utility/misc/endian.hpp
class.
Could you check if in new versions it works?

**Comment by Ru13en** [comment]
Hi,
I've found the solution for this issue, please check #149.
Best regards
