### ISSUE TITLE
Use spectra or scan instead of peaks

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#15]
Once respective generics have been added to `BiocGenerics`, allow `spectra()` and/or `scans()` in addition (instead of) `peaks(.)`.

**Comment by lgatto** [comment]
Although I think this would be good, I think we should avoid any confusion and keep things have always been.

**Comment by jotsetung** [comment]
`spectra` would be more intuitive - eventually put the `peaks` functionality into `spectra`, call `spectra` in the `peaks` method and deprecate it to allow users to adopt to the new method?

**Comment by lgatto** [comment]
The signature is `peaks(object, scans)`; this would then become `scans(object, scans)`. 
The former means `give me the peaks of these scans in this object`, which makes sense, considering the new `give me the scans of these scans in this object`. Still up for it?

**Comment by lgatto** [comment]
Done in 4de273f5c90dd0df4bddebe65bf836ec7999e9a4. Currently both supported. We could consider deprecating `peaks`.

**Comment by jotsetung** [comment]
You think `scans` is better than `spectra`?

**Comment by lgatto** [comment]
> You think `scans` is better than `spectra`?

Shit - will fix.
