### ISSUE TITLE
Fix writing of non-valid mzML files

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#151]
The mzML files currently written using mzR/proteowizard are not valid according to the OpenMS `XMLValidator`.

Will check and fix.

**Comment by jotsetung** [comment]
Things to fix (applies to both `writeMSData` and `copyWriteMSData`:
+ [ ] empty content for `sourceFile` not allowed: if no source files are provided, the element should not be written (i.e. `<sourceFileList count="0">` is not allowed).
+ [ ] `cvRef="??"` is not allowed - that's the default in proteowizard for *unknown*. In case, just don't write any cv param if it is unknown.
+ [ ] `defaultDataProcessingRef` is required within the `spectrumList` element. This should point to the last `dataProcessing` element (which will be mzR).
+ [ ] If no chromatographic data is written, `<index name="chromatogram">` should also not be added to the file.

**Comment by jotsetung** [comment]
Example code used for the validation of the mzML format (note that using `copyWriteMSData` the `sourceFileList` is correctly added).
```r
library(mzR)
fl <- system.file("proteomics", "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz",
                  package = "msdata")
msf <- openMSfile(fl, backend = "pwiz")
pks <- peaks(msf)
hdr <- header(msf)
close(msf)

out_f <- "mzML-input-copyWriteMSData.mzML"
copyWriteMSData(out_f, original_file = fl, header = hdr, object = pks,
                backend = "pwiz", outformat = "mzml")
```

**Comment by sneumann** [comment]
The OpenMS `FileInfo -in mzML-input-copyWriteMSData.mzML -v` complains about
several things. XML File fixing in this case requires:
```
diff -r1.1 ./mzML-input-copyWriteMSData.mzML
46c46
<         <cvParam cvRef="??" accession="??:0000000" name="CVID_Unknown" value=""/>
---
>         <userParam name="CVID_Unknown" value=""/>
105c105
<       <spectrumList count="509">
---
>       <spectrumList count="509" defaultDataProcessingRef="pwiz_Reader_conversion">
23673,23674d23672
<     </index>
<     <index name="chromatogram">
```

After fixing some of the XML structure, the semantic validation fails with:
```
Validating mzML file against XML schema version 1.1.0
Success - the file is valid!

Semantically validating mzML file:
Error: Violated mapping rule 'sourcefile_must' at element '/mzML/fileDescription/sourceFileList/sourceFile', 3 term(s) should be present, 1 found!
Error: Violated mapping rule 'sourcefile_must' at element '/mzML/fileDescription/sourceFileList/sourceFile', 3 term(s) should be present, 0 found!
Error: Violated mapping rule 'software_must' at element '/mzML/softwareList/software', 1 term(s) should be present, 0 found!
Error: CV term must have a unit: MS:1000528 - lowest observed m/z
Error: CV term must have a unit: MS:1000527 - highest observed m/z
Error: CV term must have a unit: MS:1000504 - base peak m/z
Error: CV term must have a unit: MS:1000505 - base peak intensity
Error: Unit CV term not allowed: UO:0000010 - second of term MS:1000927 - ion injection time
Error: Violated mapping rule 'spectrum_must' at element '/mzML/run/spectrumList/spectrum', 2 term(s) should be present, 1 found!
```

An HTML file of the mapping file can be created with `CVInspector -cv_files CV/psi-ms.obo CV/unit.obo CV/goslim_goa.obo -cv_names MS UO GO -mapping_file MAPPING/ms-mapping.xml  -html /tmp/mzML_mapping_and_cv.html` and is stored at https://msbi.ipb-halle.de/~sneumann/mzML_mapping_and_cv.html

**Comment by sneumann** [comment]
Here are some `sed` expressions to fix across all spectra
```
sed -i -e 's/accession="MS:1000927" name="ion injection time" value="\([0-9.e-]*\)" unitCvRef="UO" unitAccession="UO:0000010" unitName="second"/accession="MS:1000927" name="ion injection time" value="\1" unitCvRef="UO" unitAccession="UO:0000028" unitName="millisecond"/' mzML-input-copyWriteMSData.mzML 

sed -i -e 's#observed m/z" value="\([0-9.e-]*\)"#observed m/z" value="\1" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"#' mzML-input-copyWriteMSData.mzML

sed -i -e 's#base peak m/z" value="\([0-9.e-]*\)"#base peak m/z" value="\1" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"#' mzML-input-copyWriteMSData.mzML 

sed -i -e 's#base peak intensity" value="\([0-9.e-]*\)"#base peak intensity" value="\1" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"#' mzML-input-copyWriteMSData.mzML 

sed -i -e 's#          <cvParam cvRef="MS" accession="MS:1000511" name="ms level"#          <cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum"/>\n          <cvParam cvRef="MS" accession="MS:1000511" name="ms level"#' mzML-input-copyWriteMSData.mzML 
```
Plus some manual editing, the file `mzML-input-copyWriteMSData-fixed.mzML`
in the directory created in https://github.com/sneumann/xcms/issues/268#issuecomment-374565378
validates fine.

**Comment by jotsetung** [comment]
I'd say we fix first the validity check and then the semantic checks.

Question @sneumann, to fix the `<index name="chromatogram">` I need to change code in proteowizard's `Serializer_mzML.cpp`. What is the best approach there to make this permanent? Fixing it in the currently included proteowizard code would be gone next time an updated proteowizard is included.

**Comment by sneumann** [comment]
Let's fix locally first, and submit the patch upstream. Since we have the Validation output
of pwiz generating non-validating mzML, acceptance should be straightforward.

**Comment by jotsetung** [comment]
OK, with https://github.com/HUPO-PSI/psi-ms-CV/releases/tag/v4.1.2 we have now a CV Term ID for `mzR` (MS:1002869), `MSnbase` (MS:1002870) and `CAMERA` (MS:1002871) (thanks @sneumann for requesting that).

Problem is these are not yet known to proteowizard (for sure not in the proteowizard code that is included in `mzR`), so providing them results in an error:
```r
Error in pwizModule$writeSpectrumList(file, outformat, header, object,  : 
  Invalid cvParam accession "1002869"
```

An immediate solution would be to hack them into `src/pwiz/data/common/cv.hpp` and `src/pwiz/data/common/cv.cpp`. I'm however not sure how frequently the proteowizard code within `mzR` is updated - if at all.
@sneumann , @lgatto what do you think?

**Comment by sneumann** [comment]
Hi, pwiz code in mzR is updated when needed. E.g. when it is too old for current compilers. 
Hacking them into `cv.hpp` is a usable option. Yours, Steffen

**Comment by lgatto** [comment]
If a latest pwiz code base has the new CV terms, it might be worth considering an update, rather then hacking them into old `cv.hpp`. What do you think?

**Comment by jotsetung** [comment]
I guess we might have to wait a little for the proteowizard that includes the most recent obo - I don't know how frequently the guys update the `cv.hpp` and `cv.cpp`. In any rate - I've hacked the files in commit https://github.com/jotsetung/mzR/commit/1f0ec320da4448d5092b99922bc063f813782423 to have an immediate solution (that can also be thoroughly tested prior to the BioC release).

**Comment by jotsetung** [comment]
I'm closing this issue now. Note that, while we write now valid `mzML` files with `writeMSData`, we might still end up with non-valid `mzML` files using `copyWriteMSData`, if the original file is not valid.

**Comment by sneumann** [comment]
Pushed as 2.13.6 to both upstream and origin. Yours, Steffen
