### ISSUE TITLE
mascot mzid file doesnt read

### ISSUE THREAD

**Issue by adder** [sneumann/mzR#16]
When I try to read this file ( https://www.dropbox.com/sh/nuwvqlc9bvg0ui0/AABG_3cED_Dm-o8tmjBp8RpWa?dl=0 ) I get this error:
```
> dat = openIDfile('./F004497.mzid')
Error: [References::resolve()] Failed to resolve reference.
  object type: N4pwiz9identdata7ContactE
  reference id: PERSON_DOC_OWNER
  referent list: 4
    
    
    ORG_MSL
    ORG_DOC_OWNER
```

The file could be read succesfully with `mzID`

sessioninfo 
```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] mzID_1.4.1          pracma_1.7.9        MSnbase_1.14.1     
 [4] BiocParallel_1.0.0  mzR_2.0.0           Rcpp_0.11.3        
 [7] Biobase_2.26.0      BiocGenerics_0.12.1 MSGFplus_1.1.3     
[10] dplyr_0.4.1        

```

**Comment by lgatto** [comment]
Thanks for the report. I see you use Mascot version 2.3 and your mzid file is 1.0. The latest mzid version is 1.1, which is not compatible with 1.0. 

I have done some tests locally with one of my `dat` result files; it was first exported using the same *old* Mascot to mzIdentML 1.0 and using a more up-to-date version of Mascot to mzIdentML 1.1, and I reproduce the error with the former

```r
openIDfile("~/Downloads/F074424A.mzid")
Error: [References::resolve()] Failed to resolve reference.
  object type: N4pwiz9identdata7ContactE
  reference id: PERSON_DOC_OWNER
  referent list: 4
    
    
    ORG_MSL
    ORG_DOC_OWNER
```
while the latter works fine. 

Unless @sneumann or @thirdwing have another idea, I think that `mzR::openIDfile` only support the current mzIdentML 1.1 format (this will have to be documented). `mzID`, however, supports the two versions.

I am having the same issues here in the lab, with our Mascot 2.3. The update to a more recent Mascot version is quite expensive, especially when the only feature of interest is an export functionality to a community-driven open format that Matrix Science participated developing.

**Comment by thomasp85** [comment]
It is quite horrible how x.1 versions of mzIdentML are incompatible… Have any of you looked into the proposal for 1.2? I hope it’s not equivalently messy…

**Comment by lgatto** [comment]
Actually, I think 1.2 will include some substantial changes that will not be backwards compatible. From the relevant PSI mailing list:

> We completely agree that changing the format dramatically will hurt its dissemination more than it will help. But on the other hand, we cannot rely on hacks on the long term :)

**Comment by thomasp85** [comment]
great… I think I don’t get their versioning scheme on a very fundamental level. Oh well, it’s just numbers. Hope the data still fits into the mzID class format…

**Comment by adder** [comment]
Hi, thanks for the information. I think there are some groups in the department that may have the latest mascot version.
Except for another export version, I guess there will also be some more substantial inprovements in 2.5. Else I just stick with `mzID` for import.
