### ISSUE TITLE
readMSData fails on mzML file with only <chromatogram>s

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#163]
Hi,
I have an mzML file with just a `<chromatogramList>` but no `<spectrumList>`,
where MSnbase/mzR fail reading spectrum headers. Yours, Steffen

```
> od <- readMSData("Lipidyzer Batch - 20151021124234 - 1 - 1-22766 - QC-05840.mzml")
Error in object@backend$getAllScanHeaderInfo() : 
  upper value must be greater than lower value
> traceback()
8: stop(list(message = "upper value must be greater than lower value", 
       call = object@backend$getAllScanHeaderInfo(), cppstack = NULL))
7: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x55b8fc6f9520>, 
       dll = list(name = "Rcpp", path = "/vol/R/R-devel/lib/R/library/Rcpp/libs/Rcpp.so", 
           dynamicLookup = TRUE, handle = <pointer: 0x55b8ff8d71d0>, 
           info = <pointer: 0x55b8fb8fa750>), numParameters = -1L), 
       <pointer: 0x55b8fe1ba870>, <pointer: 0x55b900270050>, .pointer)
6: object@backend$getAllScanHeaderInfo()
5: .local(object, ...)
4: mzR::header(msdata)
3: mzR::header(msdata)
2: readInMemMSData(files, pdata = pdata, msLevel. = msLevel., verbose = verbose, 
       centroided. = centroided., smoothed. = smoothed., cache. = cache.)
1: readMSData("Lipidyzer - QC-05840.mzML")
```

**Comment by jotsetung** [comment]
Note: to read chromatogram data you should use the `chromatogramHeader` and the `chromatogram` functions.

**Comment by jotsetung** [comment]
And/or the `readSRMData` from `MSnbase`.

**Comment by lgatto** [comment]
`readMSData` shouldn't fail so badly when there's no spectra though. @sneumann, could you share that file, or any file with chromatograms only, so that we can test for this.

**Comment by sneumann** [comment]
Here is that file, I had to ask for permission first. Yours, Steffen

**Comment by lgatto** [comment]
Ok, this is fixed in the latest version of `MSnbase` available on github at `https://github.com/lgatto/MSnbase/`, which depends on the latest `mzR` from github. Instead of this ugly error, it will return a warning and an empty object. 

```r
> readMSData(f0)
MSn experiment data ("MSnExp")
- - - Processing information - - -
No data loaded: Wed May 16 10:41:02 2018 
 MSnbase version: 2.7.0 
Warning message:
In readMSData(f0) :
  Dropping 1 files with spectra: Lipidyzer Batch - 20151021124234 - 1 -1-22766 - QC-05840.mzml
```
This also work when multiple files are read, but some don't have any spectra. There will be more improvements, telling the user that there's chromatographic data. 

Closing now, feel free to re-open if necessary.
