### ISSUE TITLE
mzR fails at some .mzML files; outputs Invalid cvParam accession "1002746"

### ISSUE THREAD

**Issue by shubham1637** [sneumann/mzR#170]
Hi, I am not able to get `mz` object from certain mzML files
```
filename <- "Exp1.chrom.mzML"
mz <- openMSfile(filename, backend = "pwiz")
Error in pwizModule$open(filename) : Invalid cvParam accession "1002746"
```
I can load these files in `pyopenms` but not in R using `mzR`

sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS
mzR_2.12.0

**Comment by lgatto** [comment]
Do these file contain spectra or chromatograms?

I would suggest you have a look at `MSnbase`, and in particular
-  `readMSData` to load raw MS data (works with multiple files and multiple MS levels - see the `mode` argument, where you probably will want to set `mode = "onDisk"`) 
- `readSRM` to read chromatographic and/or transition data (again, works with multiple files)

**Comment by shubham1637** [comment]
These files contain chromatograms. There was a different file  "Exp2.chrom.mzML" which I was able to load using `openMSfile`. Certain files I cannot. I think this could be related to compression. Is `openMSfile` able to open compressed mzML files?

**Comment by lgatto** [comment]
I don't know it it's related to compression - do your `Exp1.chrom.mzML` and `Exp2.chrom.mzML` files use different compressions?

**Comment by shubham1637** [comment]
I am also not sure about that. I will figure it out and let you know.

**Comment by lgatto** [comment]
Oh, and I also see that you are using an old version of `mzR` - the current release version is `2.14.0`, but I can't tell if that has any relation to the error.

**Comment by lgatto** [comment]
Could you check in your two file for the occurrence of the `1002746` term.

**Comment by shubham1637** [comment]
If I uncompress the file using `OpenMS` and then use `mzR`; it is able to provide `mz` object. I think the issue was because of the file-compression.

**Comment by lgatto** [comment]
Could you clarify what you mean by *uncompress with OpenMS*. Do you mean that the compression of the data inside the file, or the whole file?

**Comment by shubham1637** [comment]
It is data inside the file. 
The error I was getting from `OpenMSfile` was Cvparam 1002746.
I found the following description of this error:
id: MS:1002746
name: MS-Numpress linear prediction compression followed by zlib compression
def: "Compression using MS-Numpress linear prediction compression and zlib." [https://github.com/ms-numpress/ms-numpress]

**Comment by lgatto** [comment]
Yes, that is the definition of that CV parameter. It would be helpful for us to know it you also have it in the second file.

**Comment by shubham1637** [comment]
If I search for the CV param on compressed file, I get the following output
```
grep "accession=\"MS\:1002746\"" exp1.chrom.mzML | head
<cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
						<cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
						<cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
```

After uncompressing it, I do not see the above output.

**Comment by lgatto** [comment]
What about  `exp2.chrom.mzML`?

**Comment by shubham1637** [comment]
No output for `grep "accession=\"MS\:1002746\"" exp2.chrom.mzML | head` either.

**Comment by lgatto** [comment]
Thank you for the clarification.

**Comment by mwgard** [comment]
I have run into the same error with mzR (openMSfile function) and MSnBase (readMSData) for the following cvParam accessions: 
MS:1002814, MS:1002815, MS:1002816, MS:1002817, MS:1002818, MS:1002819
All of these cvParam accessions are defined in a more recent version of psi-ms.obo (data-version: 4.1.18; date: 26:10:2018 15:06), but are missing from mzR/src/pwiz/data/common/cv.hpp. 
These cvParam accessions are in mzML files generated using ProteoWizard (v3.0.18254.c18e43d39) to convert Bruker TDF files (timsTOFpro instrument) to mzML using the '--combineIonMobilitySpectra' flag. 
I was able to replace these 6 cvParam accessions in the mzML files with other values, which allowed the mzML files to then be opened successfully with mzR.

**Comment by Tony-II** [comment]
Hello,

i think I have a problem relateted to this issue:

I am trying to open a mzML file, which was converted from .wiff to .mzML by using the (at the time of writing) latest proteowizard installer: pwiz-setup-3.0.19190.28954c376-x86_64.msi 

Afterwards I tried to read the file in R 3.6.1, 64 bit by readMSData(..) and I get the following error:

**Error in object@backend$getAllChromatogramHeaderInfo() : 
  Invalid cvParam accession "1003019"**

Having a look in the mzML file reveals, that the error is in row 274680: 

![image](https://user-images.githubusercontent.com/50142679/61292813-818d4280-a7d2-11e9-9eba-ad04ac4cdb93.png)

Packages from sessionInfo
![image](https://user-images.githubusercontent.com/50142679/61292874-abdf0000-a7d2-11e9-8103-791b9ada9742.png)


Any idea on that?

thanks
Tony

**Comment by sneumann** [comment]
Hi, indeed, the inknown term is 
https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L19592
which I've never seen before. Which instrument is that ? Some kind of Agilent ?
The short-term solution is to delete manually from (including) `<chromatogram ... pressurethingy>`
up to (and including) `</chromatogram>` .
The alternative hack is to overwrite the entire offending line `<chromatogram ... pressurethingy>` with the 
`<chromatogram ... basepeakthingy>` from a few lines above, since we don't use that pressure anyway. 

The better solution is that we manage to get an updated pwiz in this branch 
https://github.com/sneumann/mzR/tree/feature/updatePwiz20190301
to work. But not during my vacation. 

Yours, Steffen

**Comment by jorainer** [comment]
I've the same problem now with an mzML file converted with a recent proteowizard (from the official docker image). Is there any progress on including an updated proteowizard into `mzR`? An alternative would be to update/replace *just* the `pwiz/data/common/cv.hpp` and the corresponding `cv.cpp` file...

**Comment by sneumann** [comment]
Adressing in https://github.com/sneumann/mzR/pull/210

**Comment by shubham1637** [comment]
> If I search for the CV param on compressed file, I get the following output
> 
> ```
> grep "accession=\"MS\:1002746\"" exp1.chrom.mzML | head
> <cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
> <cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
> <cvParam cvRef="MS" accession="MS:1002746" name="MS-Numpress linear prediction compression followed by zlib compression" />
> ```
> 
> After uncompressing it, I do not see the above output.

Hi, I think it would be good feature to have in mzR as compressed files are lighter. I found the [C++ code](https://github.com/ms-numpress/ms-numpress/blob/8a2dcecc3fd307f32425a11cecd63203f0697b55/src/main/cpp/MSNumpress.hpp#L140) that could be used to decompress the chromatogram while extracting them.
Could you guide where can I add the code and create a pull-request?
