### ISSUE TITLE
Citing mzR

### ISSUE THREAD

**Issue by mobiusklein** [sneumann/mzR#171]
Hello,

I'm writing an article about writing the various PSI-HUPO XML formats across different languages. I'm trying to cite mzR specifically, for providing those capabilities to R by binding ProteoWizard. There is substantial effort involved in making the bindings *work*, but I couldn't find a citation for mzR itself, just it suggesting citations for ProteoWizard and supporting publications. 

Is there a citation for mzR specifically, or should I cite MSnBase instead?

Thank you

**Comment by sneumann** [comment]
Hi, Thanks for checking how to do the proper citations.

mzR was described first as part of the proteowizard 2.0 paper in nature Biotech.

http://dx.doi.org/10.1038/nbt.2377

Yours, Steffen

---
I blame Android for the brevity and typos

**Comment by lgatto** [comment]
If you wanted to cite the package specifically, you could also use the following, which is the typical type of citations produced for packages.

> Bernd Fischer, Steffen Neumann, Laurent Gatto, Qiang Kou, Johannes Rainer. mzR, a parser for netCDF, mzXML, mzData and mzML and mzIdentML files. R package version 2.14.0. DOI: 10.18129/B9.bioc.mzR

**Comment by mobiusklein** [comment]
Thank you, that clarifies things.
