### ISSUE TITLE
Problems compiling mzR

### ISSUE THREAD

**Issue by jhusarven** [sneumann/mzR#175]
I am getting the following error when I try to install mzR in R:
g++ -std=gnu++11 -I/cm/shared/apps/R/3.4.3/gcc/5.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/home-4/ssabunc1@jhu.edu/R/x86_64-pc-linux-gnu-library/3.4/gcc/5.4/Rcpp/include" -I"/home-4/ssabunc1@jhu.edu/R/x86_64-pc-linux-gnu-library/3.4/gcc/5.4/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c RcppPwiz.cpp -o RcppPwiz.o
In file included from ./boost/boost/math/special_functions/sign.hpp:16:0,
                 from ./boost/boost/lexical_cast/detail/inf_nan.hpp:34,
                 from ./boost/boost/lexical_cast/detail/converter_lexical_streams.hpp:64,
                 from ./boost/boost/lexical_cast/detail/converter_lexical.hpp:53,
                 from ./boost/boost/lexical_cast/try_lexical_convert.hpp:34,
                 from ./boost/boost/lexical_cast.hpp:32,
                 from ./pwiz/utility/misc/optimized_lexical_cast.hpp:29,
                 from ./pwiz/data/common/ParamTypes.hpp:29,
                 from pwiz/data/msdata/MSData.hpp:29,
                 from pwiz/data/msdata/MSDataFile.hpp:29,
                 from RcppPwiz.h:12,
                 from RcppPwiz.cpp:1:
./boost/boost/math/tools/config.hpp:339:36: fatal error: boost/detail/fenv.hpp: No such file or directory
    #include <boost/detail/fenv.hpp>
                                    ^
compilation terminated.

I am wondering whether this is caused by a missing file. 

Best

Sarven

**Comment by sneumann** [comment]
Hi, can you provide the solution for the records ? Thanks, Steffen

**Comment by jhusarven** [comment]
The problem was that the boost library was missing from our server. Once the netcdf and the boost libraries were installed, the package installed and the mzR library can be loaded.

Sarven
