### ISSUE TITLE
Compilation failure on Linux, unknown symbol

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#177]
Hi, 
there is a build failure on the BioC build farm:
http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/malbec1-install.html
and also the Debian docker images (see https://github.com/Bioconductor/bioc_docker/issues/56)

where the reason is that we have multiple - and incompatible! - versions of `libhdf5` 
in the link stage: 
```
/usr/local/lib/R/site-library/Rhdf5lib/lib/libhdf5_cpp.a 
/usr/local/lib/R/site-library/Rhdf5lib/lib/libhdf5.a 
/usr/local/lib/R/site-library/Rhdf5lib/lib/libsz.a 
-lz -L/opt/lib/hdf5-18/lib/ -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl 
-lhdf5 -lpthread -lsz
```
The first are defined by `echo 'Rhdf5lib::pkgconfig("PKG_CXX_LIBS")'| "${R_HOME}/bin/R" --vanilla`
the second are defined in through `nc-config --libs`

**Comment by sneumann** [comment]
This will magically disappear once we have merged 
https://github.com/sneumann/mzR/tree/featureRemovelibnetCDF

**Comment by lgatto** [comment]
I have meged/pushed to Bioc.
