### ISSUE TITLE
Migrating from libnetcdf to ncdf4

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#178]
Hi, to avoid the recurring Linking Hell with HDF5 and netCDF,
we could drop https://github.com/sneumann/mzR/blob/master/src/rnetCDF.c
and rewrite https://github.com/sneumann/mzR/blob/master/R/methods-mzRnetCDF.R
to use https://cran.r-project.org/package=ncdf4 instead.
Yours, Steffen

**Comment by lgatto** [comment]
I would definitely be in favour of re-using the `ncdf4` package to limit external dependencies on our direct end, but won't be able to commit time to rewrite the `mzRnetCDF` methods.

**Comment by sneumann** [comment]
I have a first go at 
https://github.com/sneumann/mzR/commit/dfbd825f35f1c66cf69c980662a6bc3b02413f4b
please beat it and report shortcomings before we can cleanup and merge
