### ISSUE TITLE
netCDF: Error in R_nc4_open: Too many open files

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#185]
Seems we have a bug coming in with https://github.com/sneumann/mzR/pull/179 : netCDF file handles are never closed:

```r
library(mzR)
library(msdata)
fl <- system.file("cdf/ko15.CDF", package = "msdata")

for (i in 1:1000) {
   cat(i, "\n")
   msf <- openMSfile(fl)
   tmp <- header(msf)
   close(msf)
}
1
2
3
...
510 
511 
Error in R_nc4_open: Too many open files
Error in nc_open(filename, write = FALSE) : 
  Error in nc_open trying to open file /Users/jo/R/2018-11/R-3.6-devel-Bioc3.9-devel/lib/R/library/msdata/cdf/ko15.CDF

```

sessionInfo:

```r
> sessionInfo()
R Under development (unstable) (2018-11-02 r75540)
Platform: x86_64-apple-darwin18.2.0/x86_64 (64-bit)
Running under: macOS Mojave 10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] msdata_0.23.0 mzR_2.17.0    Rcpp_0.12.19 

loaded via a namespace (and not attached):
[1] compiler_3.6.0      ProtGenerics_1.15.0 parallel_3.6.0     
[4] Biobase_2.43.0      codetools_0.2-15    ncdf4_1.16         
[7] BiocGenerics_0.29.1

```

**Comment by jotsetung** [comment]
Seems the problem is here https://github.com/sneumann/mzR/blob/master/R/netCDF.R#L20 `nc_close` is commented out in `netCDFClose` hence CDF files are never closed. Was there any special reason to comment that line out @sneumann ? I did not get any errors in `R CMD check` of `mzR`, `xcms` and `MSnbase` if that line is not commented out. Also, the error above would be fixed.

**Comment by sneumann** [comment]
Blatant omission of my side, of course they must be closed. 
We should also figure out how to push the fix into the release branch,
I guess I'll have to do that.

**Comment by jotsetung** [comment]
To push to the release branch:
on you machine (assuming you have remote *master* pointing to github and rempte *upstream* to Bioconductor):
```
git fetch --all
git checkout RELEASE_3_8
```
Fix the code in the release branch, increase the package version, commit the changes and push them to bioconductor
```
git push upstream RELEASE_3_8
```
(ev also `git push master RELEASE_3_8` to have the branch in github.

**Comment by sneumann** [comment]
Need to re-visit, and find why the patch failed in travis:
https://travis-ci.org/sneumann/mzR/builds/451448971

**Comment by sneumann** [comment]
Ok, was a temporary lapse. I'll merge now.

**Comment by sneumann** [comment]
Now also backported to RELEASE_3_8

**Comment by rromoli** [comment]
@sneumann is it possible to patch also the devel release (RELEASE_3_9)?

**Comment by jotsetung** [comment]
@rromili do you get this error if you use `mzR` or `xcms`? I've fixed a related bug in `xcms` (see https://github.com/sneumann/xcms/issues/363 for details).

**Comment by rromoli** [comment]
I get this error using xcms ( version 3.4.4)

**Comment by jotsetung** [comment]
Can you please install `xcms` from github (for Bioconductor 3.8).
```r
devtools::install_github("sneumann/xcms", ref = "RELEASE_3_8")
```

That will install version 3.4.5 which should fix the problem.

**Comment by rromoli** [comment]
Problem fixed! Thanks!!
