### ISSUE TITLE
Failed to install mzR

### ISSUE THREAD

**Issue by sanbonmatsu** [sneumann/mzR#188]
After installing zlib, hdf5 and netcdf (both C and C++ library) into /home/myname/local , and manually installing ncdf4 by "R CMD INSTALL --configure-args="--with-nc-config=/home/myname/src/netcdf-c-4.6.2/nc-config" ncdf4_1.16.tar.gz", I tried to install mzR by "BiocManager::install("mzR", version = "3.8")", but failed. Here is the link to the message. 
https://github.com/sanbonmatsu/Errors/blob/master/mzRerror.Rout
Thanks!

**Comment by sneumann** [comment]
Hi, which OS and which gcc version is that ? Yours, Steffen

**Comment by sanbonmatsu** [comment]
Thank you for your reply!
Operating System: Red Hat Enterprise Linux
Kernel: Linux 3.10.0-957.1.3.el7.x86_64
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

Thank you!
Xiao

**Comment by sneumann** [comment]
Actually, you are using Intel's `icpc` as compiler. Can you compile with gcc ?

**Comment by sanbonmatsu** [comment]
Following your suggestion, I created ~/.R/Makevars with the following entries to override the C and C++ compiler used by R

CC=gcc
CXX=g++
CXXFLAGS= -g -O2
CXX11=g++
CXX11FLAGS= -g -O2
CXX11STD= -std=c++11

After that, mzR was successfully installed!
Thank you for your help!

Xiao

**Comment by sneumann** [comment]
Great that it worked for you! Yours, Steffen
