### ISSUE TITLE
add protein length column to psms output

### ISSUE THREAD

**Issue by sgibb** [sneumann/mzR#19]
The mzIdentML format offers an attribute "length" (stores the number of bases of a protein, e.g. `<DBSequence ... length="512">`). It would be nice if `psms` could return this attribute as additional column.

This is needed for some label-free quantitation algorithms in `MSnbase` (see e.g. https://github.com/lgatto/MSnbase/pull/48).

**Comment by lgatto** [comment]
Commit `bff67caa430980ed5e04e08240ece1bce945e536` adds a columns `DBseqLength` to the `psms` `data.frame`.
