### ISSUE TITLE
Debian issue after upgrade to Buster

### ISSUE THREAD

**Issue by rromoli** [sneumann/mzR#201]
HI, I get several issue after I upgrade my workstation to Debian 10.

```
> library(mzR)
Loading required package: Rcpp
Error: package or namespace load failed for ‘mzR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/ncdf4/libs/ncdf4.so':
  libnetcdf.so.11: cannot open shared object file: No such file or directory

```

If I try to load other related package such as xcms, but I get the same error. I see that Debian 10 run  libnecdf13 so I think the problem is related.

What should I do?

**Comment by jorainer** [comment]
Try re-installing the ncdf package: `BiocManager::install("ncdf4")`.

**Comment by rromoli** [comment]
Thanks, I solved reinstalling ncdf4 from within R and reinstalling libnetcdf-dev from linux term. 
Thanks
