### ISSUE TITLE
mzR on a 64bits Ubuntu 18.04

### ISSUE THREAD

**Issue by vliviu** [sneumann/mzR#221]
Hi, I'm trying to install using BioConductor mzR in a 64bits machine (gcc/ g++ 7.5) and I get this error:
mzR.so: No symbol version section for versioned symbol `memcpy@GLIBC_2.27'.
P.S I've installed  ncdf4 and rhdf5 dependencies ... didn't help.
Thank you in advance for your feedback, Liviu

**Comment by lgatto** [comment]
I have the same system and didn't have any issue. What's your `sessionInfo()` output?

**Comment by vliviu** [comment]
I have solved the problem. `BiocManager::install("Rhdf5lib")`  did the trick.
If Rhdf5lib was specified in prerequisites and I haven't seen it- my bad ! Thank you again Steffen for your magnificent work !

**Comment by lgatto** [comment]
It's specified in the `LinkingTo` field
![2020-05-25-142422_894x99_scrot](https://user-images.githubusercontent.com/384198/82812564-8fe8c800-9e93-11ea-8d9f-3ee368a6a404.png)

**Comment by sneumann** [comment]
My guess would've been that there were different versions of C/C++ compilers used between installing mzR now and its dependencies ncdf4 or more likely rhdf5 causing that mismatch/unresolved symbol(s), possibly when upgrading BioC and/or Ubuntu.  Yours, Steffen
