### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by lingzili** [sneumann/mzR#223]
Hello, I have encountered the following error message when using BiocManager::install("mzR"):

Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing package(s) 'mzR'
trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/windows/contrib/3.6/mzR_2.20.0.zip'
Content type 'application/zip' length 7738988 bytes (7.4 MB)
downloaded 6.8 MB

Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 7168337 != reported length 7738988
2: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'mzR/DESCRIPTION', probable reason 'No such file or directory'

Afterwards, I downloaded mzR_2.22.0.tar.gz and try to install it on my Windown machine, still I encountered the following problem:

* installing *source* package 'mzR' ...
** using staged installation
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture

Could you please let me know how to solve this issue? Many thanks in advance! :)

**Comment by sneumann** [comment]
Hi, quick guesses from phone...

Regarding second error, on windows you shouldn't need to compile from source.

Regarding first error :seems your download ended too early?

Yours Steffen


I blame Android for the brevity and typos

**Comment by lingzili** [comment]
Hello, Steffen,

Thanks so much for the quick response!

I solve the problem of mzR installation by updating my R from 3.6.2 to 4.0.2, and then re-install all the existing packages on my Windows machine. Now it works fine, although I do not know why the installation did not work for R version 3.6.2...

Best regards,

Lingzi

**Comment by sneumann** [comment]
Great, thanks for the feedback ! Yours, Steffen
