### ISSUE TITLE
docker image for mzR 

### ISSUE THREAD

**Issue by shubham1637** [sneumann/mzR#234]
Hi,
    Is there any docker image for installing mzR? I am trying to run mzR on HPC using singularity.

Thanks!

**Comment by lgatto** [comment]
Yes, the [Bioconductor containers](http://bioconductor.org/help/docker/) should have `mzR`.

**Comment by jorainer** [comment]
Just to expand on @lgatto's reply - the docker containers have all the required libraries to install `mzR`, so you'll have to create a *sif* image from the Bioconductor container (with `singularity pull`) and use the same setup as described for the bioconductor containers (i.e. bind an external directory to the singularity/docker to install all R packages there).  I'm also using singularity on our clusters with that, works well.
