### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by rromoli** [sneumann/mzR#237]
Hi,
My name is Riccardo. I get a serious problem with mzR while upgrading form R
3.x.x (do not remember..) to R 4.0.3. I use a macbook pro with 500gb HDD, 4GB ram and Debian 10 (up to date). This is the error:

```
cc1plus: out of memory allocating 16777144 bytes after a total of 223604736 bytes                                                                            
make: *** [/usr/lib/R/etc/Makeconf:181: pwiz/data/common/Unimod.o] Error 1
ERROR: compilation failed for package ‘mzR’
* removing ‘/usr/local/lib/R/site-library/mzR’

```
I tried to install the package both from inide R, using `BiocManager::install()`, then from outside R, using `R CMD INSTALL`, but I always get the same error.
 This is my sessionInfo:

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.3      tools_4.0.3        

```

Hope you can help me.

All the Best
Riccardo

**Comment by sneumann** [comment]
Hi, can you try to re-run the failing c++ compiler call, but omit the `-O2` switch ? 
In such cases I `cd mzR/src/` and then copy&paste the failed compiler call, and subsequently remove suspicious (prone to memory consumption) compiler switches. Optimisation plus advanced C++ features can lead to such out of memory situations. Yours, STeffen

**Comment by rromoli** [comment]
After several, at least 4, reboot of my laptop, I've been able to install mzR... I haven't done anything between the reboot so I do not understand what happens...

**Comment by sneumann** [comment]
Glad you fixed it, thanks for reporting back ! Yours, Steffen
