### ISSUE TITLE
Build failure on Fedora with clang

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#263]
Hi, we have a report on a build failure on Fedora (see 
https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang for the actual setup)
and [mzR.log](https://github.com/sneumann/mzR/files/8243040/mzR.log) for the logs. 

The actual error seems to be 
```
clang++ -std=gnu++11 -I"/data/gannet/ripley/R/R-clang/include" -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG    -I'/data/gannet/ripley/R/test-clang/Rcpp/include' -I'/data/gannet/ripley/R/test-clang/Rhdf5lib/include' -isystem /usr/local/clang/include   -fpic  -g -O3 -Wall -pedantic -frtti  -c pwiz/data/common/BinaryIndexStream.cpp -o pwiz/data/common/BinaryIndexStream.o
pwiz/data/common/BinaryIndexStream.cpp:159:15: error: cannot assign to non-static data member within const member function 'operator[]'
        next_ = _Off * value_size_;
        ~~~~~ ^
```
Yours,
Steffen

**Comment by chambm** [comment]
I'm not even sure what that member function is there for. It doesn't seem to be used anywhere in the code. Making it non-const doesn't seem right, so just removing it outright is probably what I'll do.
