### ISSUE TITLE
Support of EAD DDA files

### ISSUE THREAD

**Issue by htmonkey** [sneumann/mzR#277]
Hi, it seems that mzR isn't extracting MSn spectra acquired by DDA-EAD on a SCIEX ZenoTOF 7600. All is fine with DDA-CID runs, but Msn spectra are reported empty in the case of EAD.

Exemplary file: https://polybox.ethz.ch/index.php/s/M5qcKW5NiJYU7Xs
```
of <- openMSfile('EAD_30msec15KE_SPLASH_2.mzML')
sh <- header(of)
sh2 <- sh[sh$msLevel == 2, ]
ms2spectra <- peaks(of, sh2$seqNum)
ms2spectra[1]
[[1]]
     mz intensity
```

**Comment by jorainer** [comment]
Hi Nicola,

can proteowizard (more recent versions) correctly import the data? Maybe we would need to update the proteowizard libraries within `mzR` @sneumann ?

**Comment by htmonkey** [comment]
Yes: all EAD files converted by pwiz include complete MS2 scans. I can see everything with TOPPview. mzR finds the MS2 scans, but doesn't manage to pull the MS2 spectra. 

In the meantime, I tested several files and pwiz versions. The issue doesn't seem to be related to the pwiz version, but to the file. In one case it actually worked with pwiz+mzR. Unfortunately the vast majority of DDA-EAD files doesn't. Fishy. 

Just in case, I added the raw data of a file (wiff & wiff2) to the same link.

**Comment by htmonkey** [comment]
I figured out the issue. It wasn't caused by mzR or Pwiz, but by some odd centroiding phenomenon by the SCIEX software. Funnily enough, TOPPview shows an MS2 spectrum even if the scan doesn't contain any binary data. Whatever. I'll close the issue. Thx!

**Comment by jorainer** [comment]
Thanks for letting us know!
