### ISSUE TITLE
mzR not available for R 4.2.3

### ISSUE THREAD

**Issue by jhowasmrtl** [sneumann/mzR#280]
mzR is not available for R 4.2.3.

**Comment by sneumann** [comment]
Hi, thanks for reporting, and glad it worked out so quickly :-) Yours, Steffen

**Comment by jhowasmrtl** [comment]
Yes, sorry for the less informative issue report; I had no problem installing from the instructions on the Bioconductor website, but I got the above error message when trying to install mzR by itself directly from the R console (i.e., install.packages("mzR"). If it's an issue it's a very minor one.
