### ISSUE TITLE
Fails to compile/install on Fedora 38 / R 4.3.0

### ISSUE THREAD

**Issue by c4chris** [sneumann/mzR#282]
Hello,

I tried and failed to get the mzR package to install through BioConductor in the latest release of Fedora (version 38), running R version 4.3

After applying the attached simple patch, I got it to compile and install

I do not know if it is the proper way to fix things, but here it is in case it is useful

Kind regards,
Christian

[mzR_diff.txt](https://github.com/sneumann/mzR/files/11324809/mzR_diff.txt)

**Comment by sneumann** [comment]
Hi, thanks for reporting and even sending a patch. 

If you contributed that as a pull request, we'd even see results on the continuous integration testing, 
that would speed things up on our side. Oh, and you'd be listed as contributor on the GitHub stats :-) 
If not, I'll try to get to it in the coming days. 

Yours, 
Steffen

**Comment by c4chris** [comment]
Ok, done in pull request #283

**Comment by sneumann** [comment]
This might also fix the following report by Prof. Ripley:
```
Files

pwiz/data/msdata/BinaryDataEncoder.hpp
pwiz/data/msdata/MSData.hpp
pwiz/utility/misc/BinaryData.cpp

are missing including <cstdint>, as they use std::int64_t.

It also fails to install with current LLVM clang 16.0.2 unless flag
-Wno-error=enum-constexpr-conversion is passed.
```
see also comments in https://www.stats.ox.ac.uk/pub/bdr/gcc13/README.txt

Yours,
Steffen

**Comment by sneumann** [comment]
still trying to find an appropriate container for CI, r/rhub/fedora-gcc-devel has R-4.4 and only gcc-12,
so 1) fails to install via BiocManager:install and 2) not reproducing the issue .
