### ISSUE TITLE
Compilation fails: control reaches end of non-void function

### ISSUE THREAD

**Issue by saskema** [sneumann/mzR#288]
Hi,

I'm trying to install mzR 3.18 from Bioconductor. The compilation (using g++ 13.2.1) fails with 
**pwiz/data/msdata/MSData.cpp:1115:1: error: control reaches end of non-void function [-Werror=return-type]**.

Please see the full error message below:

```
pwiz/data/msdata/MSData.cpp: In member function 'virtual size_t pwiz::msdata::SpectrumList::findAbbreviated(const std::string&, char) const':
pwiz/data/msdata/MSData.cpp:1115:1: **error: control reaches end of non-void function [-Werror=return-type]
 1115 | }
      | ^**
cc1plus: some warnings being treated as errors
make: *** [/usr/lib64/R/etc/Makeconf:200: pwiz/data/msdata/MSData.o] Error 1
ERROR: compilation failed for package 'mzR'
```

My `sessionInfo()` is as follows:
```
R version 4.3.2 (2023-10-31)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Tumbleweed

Matrix products: default
BLAS:   /usr/lib64/R/lib/libRblas.so 
LAPACK: /usr/lib64/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
[1] C

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.22 compiler_4.3.2      tools_4.3.2      
```  

Please let me know, if you need any further information.

**Comment by saskema** [comment]
Adding `return size();` to line 1115 in src/pwiz/data/msdata/MSData.cpp did the trick.

I peeked at the ProteoWizard guys ;).

**Comment by FionaN-A** [comment]
> Adding `return size();` to line 1115 in src/pwiz/data/msdata/MSData.cpp did the trick.
> 
> I peeked at the ProteoWizard guys ;).

This worked for me too. THANK YOU!

**Comment by sneumann** [comment]
Does any one of you two fancy your very first PR to mzR ? The contribution guide is only mildly helpful,
but you add the fix, and in DESCRIPTION bump the version to 2.41.1 
Feel free adding yourself to `Authors@R` as `"ctb"`, as suggested in https://r-pkgs.org/description.html#sec-description-authors-at-r 
Yours,
Steffen

**Comment by saskema** [comment]
I'll gladly prepare a pull request in the course of the next week. If @FionaN-A is available earlier, that would be fine for me as well.

**Comment by sneumann** [comment]
I can confirm there is a warning on my system:
```
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG    -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/Rhdf5lib/include'     -fpic  -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/r-base-FPSnzf/r-base-4.3.3=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/r-base-FPSnzf/r-base-4.3.3=/usr/src/r-base-4.3.3-2build2 -Wdate-time -D_FORTIFY_SOURCE=3  -c pwiz/data/msdata/MSData.cpp -o pwiz/data/msdata/MSData.o
pwiz/data/msdata/MSData.cpp: In member function ‘virtual size_t pwiz::msdata::SpectrumList::findAbbreviated(const std::string&, char) const’:
pwiz/data/msdata/MSData.cpp:1115:1: warning: control reaches end of non-void function [-Wreturn-type]
 1115 | }
```
which can lead to an error given stricter CXXFLAGS. Warning is gone with #288. 
Yours, Steffen
