### ISSUE TITLE
unable to open netCDF file

### ISSUE THREAD

**Issue by jqb3644** [sneumann/mzR#289]
Hi when I try to use mzR to open a netCDF file I get the following error

Error in openMSfile("Desktop/01.CDF")
  Unable to open netCDF file.

I have tried specifying the backend as netCDF but get the same error

**Comment by lgatto** [comment]
I think the error you see is the result of the ` mzR:::netCDFIsFile()` function trying to unsuccessfully open/test your file. Are you sure about that file?

**Comment by sneumann** [comment]
Who/what wrote 01.CDF ? mzR tests presence of a few variables in the file, and if tests fail it can't open the file. Yours, Steffen

**Comment by jqb3644** [comment]
The cdf file was written by waters databridge of an mse experiment.
It was opened and read successfully by the readMSexperiment function of xcms

Which variables is mzR looking for in a netCDF file?

**Comment by lgatto** [comment]
The `MsExperiment::readMsExperiment()` function (it's not from xcms) uses the `Spectra::Spectra()` constructor, that makes us the `mzR` under the hood, so I very much doubt one works and not the other. Could you double check.

**Comment by jqb3644** [comment]
thanks for your quick responses. I've attached a screen shot of the error message I get when trying to load the same CDF file two different ways.

it works with the readMSexperiment function but not the xcmsSet or openMSfile function

![errormessage](https://github.com/sneumann/mzR/assets/158118004/c5e56339-0bb7-42ee-b966-2e0db1bca785)

**Comment by lgatto** [comment]
Could you share that test.CDF file.

**Comment by jqb3644** [comment]
unfortunately
[lockmass.zip](https://github.com/sneumann/mzR/files/14118165/lockmass.zip)
 I can't share the original file but I can share the lockmass CDF which gives me the same error

Thanks for your help

**Comment by lgatto** [comment]
No problem on my side, I can open the file with `mzR::openMSfile()` and `Spectra::Spectra()` (used by `readMsExperiment()`). 

Make sure you have an up-to-date installation.

**Comment by sneumann** [comment]
Hi, so xcms technically works fine:
```
xr <- xcmsRaw("lockmass.CDF")
# Create profile matrix with method 'bin' and step 1 ... OK
xr
#An "xcmsRaw" object with 61 mass spectra
#
#Time range: 1.9-3560.8 seconds (0-59.3 minutes)
#Mass range: 49.9416-2000.3773 m/z
#Intensity range: 1.00079-188980 
#Memory usage: 8.98 MB
```
but 61 mass spectra in 60 minutes is a bit poor. 

I also have no problem opening in mzR:
```
ms <- openMSfile("lockmass.CDF")
dim(header(ms))
#[1] 61 31
```
=> What exactly is failing for you ? 
Yours,
Steffen
