### ISSUE TITLE
Add ionInjectionTime to header output

### ISSUE THREAD

**Issue by chrishuges** [sneumann/mzR#29]
Hi,

Is it possible to add the functionality to extract the ionInjectionTime tag data from the header in converted Thermo files? It is stored in the scan header data along with the other details extracted with this function:

For example:

<scan num="9333"
     msLevel="3"
     scanEvent="0"
     masterIndex="-1"
     peaksCount="34"
     ionInjectionTime="38.6763"
     elapsedScanTime="0.13659"
     polarity="+"

I can provide working files if necessary.

Thank you.
Chris

**Comment by lgatto** [comment]
@chrishuges - could you share two small mzML and mzXML files to test this. Is this data only present for MS3 scans?

**Comment by chrishuges** [comment]
Hi,

I posted two mzXML files here: https://drive.google.com/open?id=0BwsJqOzp2I7SalZ3SDVGcHZQX1E

The ionInjectionTime tag will be present in all scans in an Orbitrap raw file. 

Thanks!

**Comment by lgatto** [comment]
Could you also add an `mzML` files - we need to make sure that things work for all (at least these two) cases.

**Comment by chrishuges** [comment]
Yes no problem. I have dropped one there now. It is a bit bigger so will take a few minutes to upload.

**Comment by sgibb** [comment]
I would prefer a solution in mzR but in the meantime you can use the following work-around (it is stupid because the file is parsed twice):
```r
library("mzR")
library("XML")

mzml <- openMSfile(file)
xml <- xmlParse(file)

accession <- function(xml, name) {
  xpathSApply(xml, sprintf("//x:cvParam[@accession='%s']", name),
              xmlGetAttr, "value",
              namespaces = c(x = "http://psi.hupo.org/ms/mzml"))
}

h <- cbind(header(mzml),
           ionInjectionTime = as.double(accession(xml, "MS:1000927")))
```
