### ISSUE TITLE
Astral data: Invalid cvParam accession "1003378"

### ISSUE THREAD

**Issue by htmonkey** [sneumann/mzR#295]
mzR 2.38.0 fails to read Astral's data because of the unknown CV terms MS:1003378 and MS:1003379. 
Maybe it's again time to update CVTranslator ;-)

**Comment by DrRuiLi** [comment]
I got this error else, it seems this problem still unresolved. 
Here I find out a temporary method for this problem.
Using an old version MSconvert (version 3.0.23163-09bc765) and add ` --ignoreUnknownInstrumentError ` when converting .raw file
This will lead to incorrect information readed, such as "model" as "Thermo Electron instrument model", but not "Astral", but not affect data analysis for mzR, xcms and Spectra.
Looking forward to the official update

**Comment by lgatto** [comment]
@sneumann - are there any instruction somewhere that describe how to update the CV terms?

**Comment by sneumann** [comment]
Hi @lgatto , maybe this script still works:
https://github.com/sneumann/mzR/blob/devel/updateCvParams.sh
Yours, Steffen

**Comment by lgatto** [comment]
@DrRuiLi - could you test the udpated version in the `cv-astral` branch, that you can install with

```
remotes::install_github("sneumann/mzR@cv-astral")
```

**Comment by DrRuiLi** [comment]
@lgatto 
I have tested this version. It's all OK now. 
Thanks for the quick reply and update!

**Comment by lgatto** [comment]
Excellent, thank you. I'll push to Bioc as soon as I have some time.
