### ISSUE TITLE
pwiz version

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#30]
Is the pwiz version recorded somewhere in the `mzR` package, possibly in `./srz/pwiz`? I would suggest to make it somehow available to developers/users.

**Comment by lgatto** [comment]
I assume this means no?

**Comment by thirdwing** [comment]
It is possible http://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/pwiz/Version.hpp

When checking out using svn, a Version.cpp can be generated. 

see https://github.com/mzdb/pwiz-mzdb/blob/master/pwiz/Version.cpp as an example

**Comment by lgatto** [comment]
Thanks.
