### ISSUE TITLE
Installing from source with the gcc 4.9.3 toolchain

### ISSUE THREAD

**Issue by meowcat** [sneumann/mzR#34]
Hi,

I am trying to set up an R installation built with the new toolchain based on gcc 4.9.3. See https://github.com/rwinlib/r-base#readme

My mzR installation fails. There is a seemingly endless stream of "undefined reference" message, but the one I see recurring is:

```
./win//x64/libpwiz.a(ChromatogramList_mzML.o):ChromatogramList_mzML.cpp:(.text+0x11b): undefined reference to `__gxx_personality_sj0'
./win//x64/libpwiz.a(ChromatogramList_mzML.o):ChromatogramList_mzML.cpp:(.text+0x167): undefined reference to `_Unwind_SjLj_Register'
./win//x64/libpwiz.a(ChromatogramList_mzML.o):ChromatogramList_mzML.cpp:(.text+0x1c8): undefined reference to `_Unwind_SjLj_Unregister'
./win//x64/libpwiz.a(ChromatogramList_mzML.o):ChromatogramList_mzML.cpp:(.text+0x302): undefined reference to `_Unwind_SjLj_Resume'
```

My Rcpp is built from source (like everything for the 4.9.3 build).

Is this a problem from my side or a possible issue with the new toolchain?

**Comment by sneumann** [comment]
Hi Michele,
./win//x64/libpwiz.a is the statically built library using the old toolchain. 
Ideally, you should be able to build a new one with the new toolchain 
using https://github.com/sneumann/mzR/blob/master/src/Makefile.libpwiz
@thirdwing is our Windows wizard, he might be able to help in case of issues.
Yours, Steffen

**Comment by meowcat** [comment]
Thanks, got it to work.

**Comment by thirdwing** [comment]
The static library is built using GCC 4.6.3
