### ISSUE TITLE
compiler/linker issue with Rcpp

### ISSUE THREAD

**Issue by mikecheng1987** [sneumann/mzR#35]
Hi there,

I have been trying to re-install a package which has a lot of dependencies including "Rcpp" and "mzR". However, it seems that the current version of "mzR" (2.4.0) has compiler/linker issue with "Rcpp" (either version 0.12.2 or 0.12.3 which is most up-to-date). Below is the error messages along with session information when I load version 0.12.2 of "Rcpp". In my other slower machine, "mzR" (2.2.1) gets along with "Rcpp" (0.12.2) so I was wondering if there is anyway I can download the source file of version (2.2.1) of mzR for the purpose of urgency on my project. 

> library(mzR)
Error : .onLoad failed in loadNamespace() for 'mzR', details:
  call: description[["RcppModules"]]
  error: subscript out of bounds
In addition: Warning messages:
1: In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.1)
than is installed on your system (0.12.2). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
2: In packageDescription(pkg, lib.loc = lib) : no package 'mzR' was found
Error: package or namespace load failed for ‘mzR’
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.2

loaded via a namespace (and not attached):
[1] ProtGenerics_1.2.1  parallel_3.2.3      tools_3.2.3        
[4] Biobase_2.30.0      BiocGenerics_0.16.1

Many thanks in advance,
Mike C.

**Comment by lgatto** [comment]
As I told you on the support site:

> I don't think that the problem is the Rcpp version. The error is
```
Error : .onLoad failed in loadNamespace() for 'mzR', details:
  call: description[["RcppModules"]]
  error: subscript out of bounds
```
> which is new however to me.
>
> I have nevertheless committed a new mzR version 2.4.1, which will be build with Rcpp 0.12.3. Please try to install it in about 24 hours and let us know if this helps.

The new version, 2.4.1 is apparently not available yet - please try again with that out once it get build. You can also build yourself, if you don't want to wait.
