### ISSUE TITLE
error reading mzML files from Sciex triple tof 6600

### ISSUE THREAD

**Issue by hpbenton** [sneumann/mzR#37]
When reading an mzML file from a sciex triple tof 6600 an error is produced : 
Invalid cvParam accession "1002533"

This seems to be coming from the psi-ms.obo file which is in pwiz/common/psi-ms.obo . I've attempted to update the file directly and recompile mzR. This didn't seem to work and produced the same error. 
I then tried the checkoutpwiz.sh and recompiled howver, mzR failed with multiple errors.

Checking the updated psi-ms.obo file the reference is as expected:
[Term]
id: MS:1002533
name: TripleTOF 6600
def: "SCIEX TripleTOF 6600, a quadrupole - quadrupole - time-of-flight mass spectrometer." [PSI:MS]
is_a: MS:1000121 ! SCIEX instrument model

**Comment by sneumann** [comment]
Thanks for reporting. We'll have a look at updating the PSI CV in mzR,
we'll have to fix a few build issues first. Yours, Steffen

**Comment by sneumann** [comment]
Hi Paul, 
The file that would have to be backported from a newer pwiz 
is https://github.com/sneumann/mzR/blob/master/src/pwiz/data/common/cv.hpp (and cv.cpp)
e.g. from https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/pwiz/data/common/cv.hpp#l7893
It could be that the conversion from psi-ms.obo -> cv.hpp is not done during build, 
but only by the pwiz folks somehow. 
Can you try copying over the new cv.* and recompiling and report back ?
Yours, 
Steffen

**Comment by hpbenton** [comment]
Hi Steffen,

Sorry for the delay on this. I put the new cv.hpp file into the directory and try to load the file again. Still got the same error though :(

Best,
Paul

**Comment by thirdwing** [comment]
@hpbenton Can you share a small part of your file to reproduce the error?

**Comment by hpbenton** [comment]
Sure but can you email me directly as the file/ dataset isn't mine. I can share a file or two with you via Dropbox or from if you email me. 

Cheers

Paul

**Comment by thirdwing** [comment]
This can be fixed by using the latest version of pwiz.

```
> library(mzR)
Loading required package: Rcpp
> mz <- openMSfile("pos_ida_hilic_control1a.mzML")
> fileName(mz)
[1] "pos_ida_hilic_control1a.mzML"
> runInfo(mz)
$scanCount
[1] 3178

$lowMz
[1] 0

$highMz
[1] 0

$dStartTime
[1] 0.279

$dEndTime
[1] 479.988

$msLevels
[1] 1 2

> instrumentInfo(mz)
$manufacturer
[1] "SCIEX"

$model
[1] "TripleTOF 6600"

$ionisation
[1] "electrospray ionization"

$analyzer
[1] "quadrupole"

$detector
[1] "electron multiplier"

> header(mz, 1)
$seqNum
[1] 1

$acquisitionNum
[1] 1

$msLevel
[1] 1

$polarity
[1] 0

$peaksCount
[1] 63

$totIonCurrent
[1] 868062

$retentionTime
[1] 0.279

$basePeakMZ
[1] 214.0891

$basePeakIntensity
[1] 20757

$collisionEnergy
[1] 0

$ionisationEnergy
[1] 0

$lowMZ
[1] 0

$highMZ
[1] 0

$precursorScanNum
[1] 0

$precursorMZ
[1] 0

$precursorCharge
[1] 0

$precursorIntensity
[1] 0

$mergedScan
[1] 0

$mergedResultScanNum
[1] 0

$mergedResultStartScanNum
[1] 0

$mergedResultEndScanNum
[1] 0
```

**Comment by sneumann** [comment]
Wow, cool. Can you also put a small description of how to update to current pwiz'es 
somewhere in the mzR documentation ?  Maybe we could have a hackers guide 
including the pre-compilation of the windows pwiz.dll

**Comment by lgatto** [comment]
Shouldn't we upgrade to the latest pwiz?

**Comment by thirdwing** [comment]
This branch (https://github.com/sneumann/mzR/tree/pwiz_upgrade/) has the latest version of pwiz.

No time for Windows now.

**Comment by hpbenton** [comment]
Yep can confirm. Latest git works with triple toe 6660 mzML files. Thanks guys :)
Cheers,
Paul

**Comment by sneumann** [comment]
Hi,
I just committed an attempt at recompiling the windows lib.
Can somebody please r cmd check
On Windows, the r instalation I'm using still can't do that.
Yours Steffen

---
I blame Android for the brevity and typos


---- Qiang Kou (KK) schrieb ----


This branch (https://github.com/sneumann/mzR/tree/pwiz_upgrade/) has the latest version of pwiz.

No time for Windows now.

**Comment by thirdwing** [comment]
http://bioconductor.org/spb_reports/mzR_2.5.3_buildreport_20160514210445.html#moscato2_buildsrc_anchor

The building error is the same with #36

**Comment by sneumann** [comment]
Hi, I'd like to merge the pwiz_upgrade tree, but have to admit 
that I miserably failed. I did git checkout devel, git svn rebase,
and then tried to git merge pwiz_upgrade and got swamped 
by merge conflicts. I hereby declare I am defeated by git :-(
and need help. Yours, Steffen

**Comment by thirdwing** [comment]
I think you can just merge https://github.com/sneumann/mzR/pull/41

**Comment by thirdwing** [comment]
@sneumann I manually merged everything (including changes in master branch) into https://github.com/sneumann/mzR/tree/pwiz_upgrade

If this branch works, please merge it into devel and master
