### ISSUE TITLE
latest mzR from svn fails to build on mac

### ISSUE THREAD

**Issue by dtenenba** [sneumann/mzR#39]
https://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/morelia-install.html

**Comment by sneumann** [comment]
Hi, this is a duplicate of #38 and fixed in 4949b521357d2659b1fe15740a940de167d5c84c
as shown on http://bioconductor.org/spb_reports/mzR_2.5.6.1_buildreport_20160419042726.html#morelia_buildsrc_anchor

**Comment by dtenenba** [comment]
I can confirm that what's in svn now builds and checks on mac. Thanks!
