### ISSUE TITLE
Support of ion mobility mzML

### ISSUE THREAD

**Issue by mvinaixa** [sneumann/mzR#44]
Hi, 

currently mzR dies on ion mobility data with 
`Invalid cvParam accession "1002476"
`
where 1002476 is "ion mobility drift time" 
http://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002476 
using mzR_2.4.1 
yours, Maria and Steffen

Please find an example data file https://www.dropbox.com/s/7m3hdw010twyun1/naringinMSlevel1.mzML?dl=0

**Comment by sneumann** [comment]
Hi, here is a reduced file, with just the first two retention times, and 50 ion mobility scans each
[naringinMSlevel1.mzML.txt](https://github.com/sneumann/mzR/files/341092/naringinMSlevel1.mzML.txt)

**Comment by lgatto** [comment]
@sneumann - is this not *onlyy* a matter of updating pwiz in `mzR`?

**Comment by hpbenton** [comment]
without diving down the rabbit hole could the cvParam scan type not just be a new column on the header?

**Comment by lgatto** [comment]
> without diving down the rabbit hole could the cvParam scan type not just be a new column on the header?

Yes, that would be the result. But we also need the cvParam to be recognised, as far as I remember.
