### ISSUE TITLE
mzR fails to install on debian with g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1

### ISSUE THREAD

**Issue by infB** [sneumann/mzR#45]
Installation of the mzR Package in R fails, because the mzr/src/Makevars script uses MAC specific parameter of the g++ compiler (-Wno-deprecated-register).

ERROR:
....
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
....

A bugfix for me was the replacement of the -Wno-deprecated-register parameter with -Wno-deprecated (mzr/src/Makevars, line 105). This might occurs in some other error, but as a quick and dirty solution in works.

sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8  
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C

**Comment by sneumann** [comment]
Hi, yes, confirmed. Also breaks windows build
http://bioconductor.org/checkResults/release/bioc-LATEST/mzR/zin2-checksrc.html
````
* checking compilation flags in Makevars ... WARNING
Non-portable flags in variable 'PKG_CPPFLAGS':
  -Wno-deprecated-register
````

**Comment by sneumann** [comment]
The non-portable compiler switch was removed in mzR-2.7.1 in commit 
c568e1b8ebbd92885a051d2b06d0a452e3ba4913 and the boost code was fixed,
while in release-3.3 in SVN commit r119743 for mzR-2.6.3 i use `-Wno-deprecated` now.
