### ISSUE TITLE
read data from file handles or connections

### ISSUE THREAD

**Issue by rmflight** [sneumann/mzR#47]
From what I can tell, mzR (and MSnBase, etc) all expect fully qualified file names.

It would be great to have methods that support `connections` from files, gzfiles, zip files, url's, etc.

**Comment by rmflight** [comment]
I'll expand as to my motivation:

We are writing an analysis pipeline for metabolomics that uses a zip file as the container to keep all of the raw and textual data together for an analysis. So being able to supply the `connection` to the *mzML* or *netCDF* file from the zip file generated by `unz` would be really handy.

My current solution is to create a *tmp* directory and `unzip` everything there, work with it, and then *zip* it back.

**Comment by lgatto** [comment]
What function are you referring to specifically? Probably `openMSfile`, but anything else?

**Comment by lgatto** [comment]
By the way, I like your use case. Just out of curiosity, is there any overhead of accessing different files or the same files multiple times through the connection created by `unz` vs unzipping it once and then accessing multiple times?

**Comment by rmflight** [comment]
I see `openMSfile`, and then the `netCDFOpen`, I think. Right now I'm depending mostly on `xcmsRaw` to do the right thing for me and load my data, and I'm pretty sure it uses `netCDF*` for `mzML` files.

**Comment by rmflight** [comment]
As far as overhead between `unz` vs unzip into a directory, I haven't looked. It may be that doing the unzip once would be better. Currently, however, we probably only need a single read, our data files are relatively small (<= 100Mb, un-centroided). 

For larger file sizes, it might make sense to do one unzip, and then access pieces using the new methods in `MSnBase`. But that should be up to the person doing the implementation, the raw accessors should just support methods for `connections` or `filenames`.

**Comment by sneumann** [comment]
Hi, my only idea to implement a connection would be to download/unzip the raw data to $TMP for non-plain files. The RAMP and pwiz backend both use proteowizard C++ code in the end, they want 
to have random access (and implement that e.g. for indexed mzML files). That also has the issue 
of cleaning up afterwards. Also, in case of a cluster, you might have shared scratch filesystems, 
where the unzip would be required only once. Bottom line is I would not implement this inside xcmsRaw/mzR . @rmflight , can you think of any convenience/wrapper/setup functions in mzR 
to make your life easier ? Yours, Steffen

**Comment by rmflight** [comment]
hmmm, ok. If everything is accessed by pwiz on the backend and it expects a
file to enable random access, then I'll take care of the file in $TMP
myself, and worry about dealing with a file handle myself for consistency
with other methods I'm writing.

Thanks for the explanation Steffen.

-Robert
