### ISSUE TITLE
File handles are not closed for backend pwiz

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#48]
Apparently, the file handles are not closed for `backend = "pwiz"`:

```{r}
library(mzR)
library(msdata)
f <- msdata::proteomics(full.names = TRUE, pattern = "TMT_Erwinia")
for (i in 1:1000) {
    msd <- mzR::openMSfile(f, backend = "pwiz")
    mzR::close(msd)
}
```
Throws the error:
```{r}
Error: failed opening file: Too many open files: unspecified iostream_category error
```

**Comment by lgatto** [comment]
@thirdwing - could you check this, please.

**Comment by thirdwing** [comment]
I think I know how to fix this, but I am really busy this week.

**Comment by lgatto** [comment]
If you could share your thoughts, I could try to have a look. Otherwise, next week is no problem at all. Thanks.

**Comment by jotsetung** [comment]
@thirdwing @lgatto : I think I fixed it! I've implemented the `close` method for `mzRpwiz` objects (that did just return `TRUE` without doing anything). In the C++ code I implemented the `close` method to release all resources; there does not seem to be an explicit `close` function to be implemented in the `pwiz` code, so I think that's all what we can do. @thirdwing can you please check if that's similar to what you had in mind?

With this I don't get the error message with too many open connections.

**Comment by lgatto** [comment]
I see you implemented the same as for the `Ramp` backend. Looks good to me. @thirdwing, any comment?

**Comment by thirdwing** [comment]
The problem is in 
https://github.com/sneumann/mzR/blob/master/R/methods-mzRpwiz.R#L142

I don't know why I just put a placeholder for pwiz. We need to 
explicitly call destructor or a close() method like 
https://github.com/sneumann/mzR/blob/master/R/methods-mzRramp.R#L66

**Comment by lgatto** [comment]
@thirdwing - and that's exactly what @jotsetung has done in #49, as far as I can see.

**Comment by thirdwing** [comment]
@jotsetung Sorry I missed your email.

@lgatto I think it is just what I thought.

**Comment by lgatto** [comment]
Great, thanks.

**Comment by jotsetung** [comment]
sorry to post to the closed issue... I was just wondering who will then push the changes also to the Bioconductor svn (and when).

**Comment by lgatto** [comment]
I will, today.

**Comment by lgatto** [comment]
Done
```
------------------------------------------------------------------------
r120458 | l.gatto | 2016-08-26 08:40:19 +0100 (Fri, 26 Aug 2016) | 1 line

upgrade pwiz and close connection for pwiz backend
```
