### ISSUE TITLE
Compilation on tokay1 / Windows

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#50]
There is an installation issues on the upcoming build machines
at https://bioconductor.org/checkResults/3.4/RPCI/bioc-LATEST/ :

```
In file included from rnetCDF.c:2:0:
rnetCDF.h:1:20: fatal error: netcdf.h: No such file or directory
 #include <netcdf.h>
                    ^
compilation terminated.
```

=> This is missing one of the `SystemRequirements: C++11, GNU make, NetCDF`,
namely NetCDF.

Yours, Steffen

**Comment by lgatto** [comment]
From Herve's email: 
```
Yes the latest localXYZ.zip (currently local323.zip) is on tokay1.

I downloaded it from

   http://www.stats.ox.ac.uk/pub/Rtools/libs.html

unzipped it in

   C:\local323

on tokay1, and followed Ripley's instructions for how to set variable
LOCAL_SOFT in R/etc/{i386,x64}/Makeconf

But it doesn't contain netcdf.

However, on that same page, Ripley also provides spatial324.zip that
seems to contain netcdf. Just installed it on tokay1 and tried to
compile mzR again. Now the "netcdf.h: No such file or directory" error
is gone... yeaaah!!!
```

**Comment by colinbrislawn** [comment]
Good afternoon,

I think I just got this error when trying to install `mzR` from bioconductor. 

```r
> biocLite("mzR")
.
.
.
In file included from rnetCDF.c:2:
./rnetCDF.h:1:10: fatal error: 'netcdf.h' file not found
#include <netcdf.h>
         ^
1 error generated.
make: *** [rnetCDF.o] Error 1
ERROR: compilation failed for package ‘mzR’
```

Is there a good programmatic way to install this? Thanks!

**Comment by sneumann** [comment]
Hi, you will need to install the netcdf development files,
which include the netcdf.h header. Not sure how OSX does that, `brew` ?

**Comment by colinbrislawn** [comment]
OK, I can install `netcdf`. I just saw you listed this and everything. My mistake. 🙄 
`SystemRequirements | C++11, GNU make, NetCDF 
`

Is there a good way to deploy `mzR` from binary, without a full build environment? That would make it a lot easier to share this software colleagues, especially those using Windows.

Thanks! I'm looking forward to trying this software.

**Comment by sneumann** [comment]
Depends on OS and your usage of `biocLite()`, see manpage
http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/BiocInstaller/html/biocLite.html

Windows can install from binary built ZIP, for Mac OS X 10.11 (El Capitan) 
there is also a binary build, Linux will always build from source.
Yours, Steffen

**Comment by colinbrislawn** [comment]
Thank you for your feedback. I've got it working on OSX!

While I could not install the binary, your suggestion of [Homebrew](https://brew.sh/) worked great.

`brew install netcdf`
```
source("https://bioconductor.org/biocLite.R")
biocLite("mzR", suppressUpdates = T)
```

Now let's try Windows...

**Comment by sneumann** [comment]
Thanks, I added the macOS instructions under https://github.com/sneumann/mzR/pull/125
Can you remind me why on macOS installing the binary 

Mac OS X 10.11 (El Capitan) from http://bioconductor.org/packages/3.6/bioc/bin/macosx/el-capitan/contrib/3.4/mzR_2.11.7.tgz
did not work ?
