### ISSUE TITLE
Compilation fails on 

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#51]
mzR has been having compilation failures on moscato1
(the old Windows builder in Seattle) since the 2.7.4 update about
2 weeks ago:
https://bioconductor.org/checkResults/3.4/bioc-LATEST/mzR/moscato1-install.html

```
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o mzR.dll tmp.def cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o RcppExports.o R_init_mzR.o rampR.o -Wl,--dynamic-linker=/ld.exe -L./win//i386 -lws2_32 -lnetcdf -lpwiz -Lc:/local323/lib/i386 -Lc:/local323/lib -LD:/biocbld/BBS-3˜1.4-B/R/bin/i386 -lR
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x72): undefined reference to `__gxx_personality_sj0'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x8b): undefined reference to `_Unwind_SjLj_Register'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0xdb): undefined reference to `_Unwind_SjLj_Unregister'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x164): undefined reference to `_Unwind_SjLj_Resume'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x1fb): undefined reference to `__gxx_personality_sj0'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x20e): undefined reference to `_Unwind_SjLj_Register'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x2a6): undefined reference to `_Unwind_SjLj_Unregister'
./win//i386/libpwiz.a(error_code.o):error_code.cpp:(.text+0x4d9): undefined reference to `_Unwind_SjLj_Resume'
...
```

These are undefined symbols because our Windows statically complied libpwiz.a 
does not match the lib static-libgcc in the used toolchain on the BioC machines.
So 1) we need to recompile libpwiz.a using the correct (which ?!) toolchain.
In the long run, with the more powerful build machine tokay1 we could try "normal" compilation
on windows, just like we have on the other ARCH. This precompiling has always been a pain.
Happy to get rid of it :-) Yours, Steffen

**Comment by thirdwing** [comment]
@sneumann I have tested the `compile_on_windows` branch on a 64-bit Windows 10 machine. It can compile and load successfully.
