### ISSUE TITLE
Error with openMSfile in RStudio

### ISSUE THREAD

**Issue by thomasp85** [sneumann/mzR#6]
The following error occurs when trying to load files using RStudio. The same files work fine with the regular R gui:

```
> ms <- openMSfile('/Users/Thomas/Desktop/004-CM_005.mzML')
Error in rampModule$open(filename, declaredOnly = TRUE) : 
  [MSDataFile::readFile()] Unsupported file format.
```

The problem has been observed with a range of files and on a range of systems (both mac and win). The problem is not constant (sometimes a file works in RStudio), but has only been observed using RStudio.

**Comment by axelmuller** [comment]
Hi,
I have a similar mzR & Rstudio problem. My problem appears to be constant and non-random though. Every time I run openMSfile() a fatal error occurs and the R session gets aborted. However, when running R from the terminal mzR works fine. 

thanks for your help,
Axel

the output for sessionInfo() is:


R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(mzR)
Loading required package: Rcpp
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 23 (Workstation Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mzR_2.5.3   Rcpp_0.12.3

loaded via a namespace (and not attached):
[1] ProtGenerics_1.2.1  parallel_3.2.3      tools_3.2.3         Biobase_2.30.0      codetools_0.2-14    BiocGenerics_0.16.1
