### ISSUE TITLE
warning: control may reach end of non-void function

### ISSUE THREAD

**Issue by sneumann** [sneumann/mzR#60]
Hi,
clang on macOS is complaining with a WARNING about 
```
* checking whether package ‘mzR’ can be installed ... WARNING
Found the following significant warnings:
  pwiz/data/identdata/Serializer_pepXML.cpp:1545:5: warning: control may reach end of non-void function [-Wreturn-type]
```
in 
https://github.com/sneumann/mzR/blob/master/src/pwiz/data/identdata/Serializer_pepXML.cpp#L1545

I guess the right return value at the end of the function should be `return true`

**Comment by lgatto** [comment]
Should these fixes not be committed up-streams? Your fix will be overwritten next time we update pwiz, won't it?
