### ISSUE TITLE
mzR cvParam accession error when reading PeptideShaker mzIdentML file

### ISSUE THREAD

**Issue by videlc** [sneumann/mzR#62]
Hey,

I am trying to open a mzid file generated by peptideshaker but when using the openIDfile command, i get this error message : 
`Error: Invalid cvParam accession "1002458"`

By opening my mzid file and searching that accession, I get one line match : 
`<cvParam cvRef="PSI-MS" accession="MS:1002458" name="PeptideShaker"/>`

Is there any way to fix this issue ?

Best regards,
Vivian

note : by looking for the error on google, this code has been seen already when willing to use PeptideShaker mzIdentML file to OpenSWATH [here](https://groups.google.com/a/umn.edu/forum/#!topic/galaxyp/XLHDegusSJE)

**Comment by thirdwing** [comment]
Normally this kind of error is due to we are using an old version of pwiz. `PeptideShaker` hasn't been added then.

We are planning to upgrade the pwiz backend soon @lgatto

**Comment by lgatto** [comment]
@videlc - I tested your `mzid` file with `mzR` earlier today and came to the same conclusion (see [here](https://github.com/thomasp85/mzID/issues/31) for background). 

@thirdwing - yes, I think we need an update anyway, as mentioned in #61.

I will get get started tonight or tomorrow.

**Comment by lgatto** [comment]
Closing this issue - update is discussed in #61

**Comment by videlc** [comment]
Just to follow up my issue.
Update solved my issue.
My initial point was to use the parser to be able to do itraq quantificaiton using reporter.

As i faced and solved some issue that were not documented before, i'll just post it there for people that might do the same in the future.

To parse : 
`
x <- openIDfile('1.mzid')
p<-psms(x)
m<-modifications(x)
`
Parsing my mzid file from peptideshaker gave me a data frame with these headers : 
`
spectrumID	chargeState	rank	passThreshold	experimentalMassToCharge	calculatedMassToCharge	sequence	modNum	isDecoy	post	pre	start	end	DatabaseAccess	DBseqLength	DatabaseSeq	DatabaseDescription	acquisitionNum
`

This had to be merged with modifications of peptides still using mzR tool 
`merged<-merge(p,m,by="spectrumID")`


The column names were changed to fit isobar's specifications.
However, when trying to use isobar with such data gave me the following issue : 
`reading id file Mascot_search_results.csv [type: ibspectra] ... done
Error in [.data.frame(id.data, , .SPECTRUM.COLS["SPECTRUM"]) : 
undefined columns selected`

Which was solved by : 

Merging "merged" file with PSM table output from peptideshaker (Default_PSM_Report.txt)

`psmtable<-read.table("*1_Default_PSM_Report.txt", header=TRUE,sep='\t')`

Then again some column renaming and merging : 
`colnames(psmtable)[3]<-"sequence"
colnames(merged)[7]<-"sequence"
merged2 <-merge(merged,psmtable,by="sequence")
q<-merged2[,c(14,1,20,4,7,6,4,30,28)]
colnames(q)[1]<-"accession"
colnames(q)[2]<- "peptide"
colnames(q)[3]<- "modif" 
colnames(q)[4]<- "charge" 
colnames(q)[5]<- "theo.mass" 
colnames(q)[6]<- "exp.mass"
colnames(q)[7]<- "parent.intens"
colnames(q)[8]<- "retention.time"
colnames(q)[9]<- "spectrum"`

Finaly, "q" was subjected to isobar with corresponding mgf file by : 
`ib <- readIBSpectra("iTRAQ4plexSpectra",q,list.files(pattern=".mgf"))`

And this tells me it should be OK now : 
`> ib
iTRAQ4plexSpectra (storageMode: lockedEnvironment)
assayData: 988 features, 4 samples 
  element names: ions, mass 
protocolData: none
phenoData: none
featureData`


Again, thanks for support and providing this to the community !

Vivian

**Comment by lgatto** [comment]
Thank you very much @videlc for following up!
