### ISSUE TITLE
pwiz backend does not close file handles

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#64]
I experienced problems processing a large dataset using `MSnbase` and was able to break that down to a problem most likely in the `header` call using the `"pwiz"` backend. A reproducible example and the error message are below. It might be related to the fact that for no dedicated `close` function seems to be present in the `pwiz` library.

```{r}
library(MSnbase)
library(msdata)
fl <- proteomics(full.names = TRUE)[2]

for (i in 1:1000) {
    cat(i, "")
    ## readMSData2
    msd <- mzR::openMSfile(fl, backend = "pwiz")
    cat(" instrumentInfo ")
    inst <- instrumentInfo(msd)
    cat(" header ")
    head <- mzR::header(msd)
    gc()
    mzR::close(msd)
    rm(msd)
    cat(" spectra ")
    ## spectra
    msd <- mzR::openMSfile(fl, backend = "pwiz")
    sp <- mzR::peaks(msd)
    gc()
    mzR::close(msd)
    rm(msd)
    cat("OK\n")
}

```
The error:
```{r}
## Error
243  instrumentInfo  header Error in object@backend$getAllScanHeaderInfo() :
  failed opening file: Too many open files: unspecified iostream_category error
>

```

There are no problems without the `header` call.

**Comment by lgatto** [comment]
According to d2f3523269f7ba7301be5de789c708b01c52a76b, a `close` should have been added to the `pwiz` backend. It's not clear to be why the header fails, or why the connection isn't closed when using `header`? Does it re-open a connection under the hood?

**Comment by jotsetung** [comment]
Yes, an additional connection is opened:
both the functions `getScanHeaderInfo` and `getAllScanHeaderInfo` open a new connection to the file _via_ a `RAMPAdapter` (`RAMPAdapter * adapter = new RAMPAdapter(filename);`), but do not delete this pointer before returning the values hence this additional connection to the file is not closed. Adding a `delete adapter;` and `adapter = NULL;` after all data has been read in solves the problem.

**Comment by jotsetung** [comment]
should I make a pull request or are you going to add these lines to the two functions?

**Comment by lgatto** [comment]
Yes please - thank you!
