### ISSUE TITLE
extract the startTimeStamp from a run

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#66]
Would be nice to add the possibility to extract also the `startTimeStamp` of a run from an mzML file (and report that e.g. also by the `runInfo` method).

**Comment by thirdwing** [comment]
It should be OK to add this and it will be better if you can provide a small file for testing.

**Comment by jotsetung** [comment]
Great! For testing you could use e.g. the _proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz_ file from the `msdata` package.

**Comment by lgatto** [comment]
```r
> library("msdata")
> f <- proteomics(full.names = TRUE, pattern = "TMT_E")
> basename(f)
[1] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
```

**Comment by stanstrup** [comment]
I'm looking for this too... Very useful for looking at batch drifts.

**Comment by lgatto** [comment]
Merged into master and pushed to Bioc devel.
