### ISSUE TITLE
Travis fails  

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#68]
Travis has been failing with a very weird error - https://travis-ci.org/sneumann/mzR

It looks like the `gcc` line has been split, leading to the

```
  /bin/bash: line 2: -shared: command not found
```
error

Any idea, anyone?

**Comment by sneumann** [comment]
So on the BioC build machines we have `g++ -std=gnu++11 -shared -L/home/biocbuild/bbs-3.5-bioc/R/lib -L/usr/local/lib -o mzR.so cramp.o [...]` so on Travis the line is missing the 'g++ -std=gnu++11` part, which on my laptop is configured in `/usr/lib/R/etc/Makeconf` via `SHLIB_CXX1XLD = $(CXX1X) $(CXX1XSTD)'. Could `SHLIB_CXX1XLD` be empty on the Travis R installation ?

**Comment by sneumann** [comment]
Reported upstream as https://github.com/travis-ci/travis-ci/issues/7017

**Comment by lgatto** [comment]
@sneumann - have you tried this
```
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing mzR installation to fail
# see https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189
# workaround stolen from https://github.com/hadley/devtools/blob/1ce84b04568ff7846c3da754f28e7e22a23c8737/.travis.yml#L23-L26
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
```

This was committed by @sgibb to [MSnbase](https://github.com/lgatto/MSnbase/commit/2d590a70cc7a25d9084ba44cd81de83e74b4cc0) and seems to work (well, it fails but for another reason).

**Comment by sneumann** [comment]
Hi, yes, this is now configured. I realised I was also too aggressive leaving out 
stuff not required for compilation, currently adding support for Ubunto 12.04, 
14.04 and will check Debian as well. Stay tuned ...

**Comment by sneumann** [comment]
Hi, confirmed to work on Ubuntu 12.04 (gcc-4.6.3) and 14.04 (gcc-4.8.2) on x86_64,
and on Debian stretch/sid (gcc-5.4.0). And - tada! - now also on Travis:
https://travis-ci.org/sneumann/mzR/builds/183959445

**Comment by lgatto** [comment]
Ok, I'll push ot Bioc asap (but probably not tonight).
