### ISSUE TITLE
mzR fails to build with gcc 6.2.1

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#72]
This [post](https://support.bioconductor.org/p/90546/) on the support site 

> I'm not sure if I should bother you team with this, apologies in case it's a bother.
>
> I'm trying gcc 6.2.1 (from devtoolset-6) with R, everything seems to work just fine, except for mzR.
> Here is failed build:

```
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o mzR.so cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o ./boost/system/src/error_code.o ./boost/regex/src/posix_api.o ./boost/regex/src/fileiter.o ./boost/regex/src/regex_raw_buffer.o ./boost/regex/src/cregex.o ./boost/regex/src/regex_debug.o ./boost/regex/src/instances.o ./boost/regex/src/icu.o ./boost/regex/src/usinstances.o ./boost/regex/src/regex.o ./boost/regex/src/wide_posix_api.o ./boost/regex/src/regex_traits_defaults.o ./boost/regex/src/winstances.o ./boost/regex/src/wc_regex_traits.o ./boost/regex/src/c_regex_traits.o ./boost/regex/src/cpp_regex_traits.o ./boost/regex/src/static_mutex.o ./boost/regex/src/w32_regex_traits.o ./boost/iostreams/src/zlib.o ./boost/iostreams/src/file_descriptor.o ./boost/thread/pthread/once.o ./boost/thread/pthread/thread.o ./boost/filesystem/src/operations.o ./boost/filesystem/src/path.o ./boost/filesystem/src/utf8_codecvt_facet.o ./boost/chrono/src/chrono.o ./boost/chrono/src/process_cpu_clocks.o ./boost/chrono/src/thread_clock.o ./pwiz/data/msdata/Version.o ./pwiz/data/common/MemoryIndex.o ./pwiz/data/common/CVTranslator.o ./pwiz/data/common/cv.o ./pwiz/data/common/ParamTypes.o ./pwiz/data/common/BinaryIndexStream.o ./pwiz/data/common/diff_std.o ./pwiz/data/common/Unimod.o ./pwiz/data/msdata/SpectrumList_MGF.o ./pwiz/data/msdata/DefaultReaderList.o ./pwiz/data/msdata/ChromatogramList_mzML.o ./pwiz/data/msdata/examples.o ./pwiz/data/msdata/Serializer_mzML.o ./pwiz/data/msdata/Serializer_MSn.o ./pwiz/data/msdata/Reader.o ./pwiz/data/msdata/Serializer_MGF.o ./pwiz/data/msdata/Serializer_mzXML.o ./pwiz/data/msdata/SpectrumList_mzML.o ./pwiz/data/msdata/SpectrumList_MSn.o ./pwiz/data/msdata/BinaryDataEncoder.o ./pwiz/data/msdata/Diff.o ./pwiz/data/msdata/MSData.o ./pwiz/data/msdata/References.o ./pwiz/data/msdata/SpectrumList_mzXML.o ./pwiz/data/msdata/IO.o ./pwiz/data/msdata/SpectrumList_BTDX.o ./pwiz/data/msdata/SpectrumInfo.o ./pwiz/data/msdata/RAMPAdapter.o ./pwiz/data/msdata/LegacyAdapter.o ./pwiz/data/msdata/SpectrumIterator.o ./pwiz/data/msdata/MSDataFile.o ./pwiz/data/msdata/MSNumpress.o ./pwiz/data/msdata/SpectrumListCache.o ./pwiz/data/msdata/Index_mzML.o ./pwiz/data/msdata/SpectrumWorkerThreads.o ./pwiz/data/identdata/IdentDataFile.o ./pwiz/data/identdata/IdentData.o ./pwiz/data/identdata/DefaultReaderList.o ./pwiz/data/identdata/Reader.o ./pwiz/data/identdata/Serializer_protXML.o ./pwiz/data/identdata/Serializer_pepXML.o ./pwiz/data/identdata/Serializer_mzid.o ./pwiz/data/identdata/IO.o ./pwiz/data/identdata/References.o ./pwiz/data/identdata/MascotReader.o ./pwiz/data/proteome/Modification.o ./pwiz/data/proteome/Digestion.o ./pwiz/data/proteome/Peptide.o ./pwiz/data/proteome/AminoAcid.o ./pwiz/utility/minimxml/XMLWriter.o ./pwiz/utility/minimxml/SAXParser.o ./pwiz/utility/chemistry/Chemistry.o ./pwiz/utility/chemistry/ChemistryData.o ./pwiz/utility/chemistry/MZTolerance.o ./pwiz/utility/misc/IntegerSet.o ./pwiz/utility/misc/Base64.o ./pwiz/utility/misc/IterationListener.o ./pwiz/utility/misc/MSIHandler.o ./pwiz/utility/misc/Filesystem.o ./pwiz/utility/misc/TabReader.o ./pwiz/utility/misc/random_access_compressed_ifstream.o ./pwiz/utility/misc/SHA1.o ./pwiz/utility/misc/SHA1Calculator.o ./pwiz/utility/misc/sha1calc.o ./random_access_gzFile.o ./RcppExports.o rampR.o R_init_mzR.o -lpthread -lnetcdf -L/usr/lib64/R/lib -lR
g++: error: cramp.o: No such file or directory
g++: error: ramp_base64.o: No such file or directory
g++: error: ramp.o: No such file or directory
g++: error: RcppRamp.o: No such file or directory
g++: error: RcppRampModule.o: No such file or directory
g++: error: rnetCDF.o: No such file or directory
g++: error: RcppPwiz.o: No such file or directory
g++: error: RcppPwizModule.o: No such file or directory
g++: error: RcppIdent.o: No such file or directory
g++: error: RcppIdentModule.o: No such file or directory
/usr/share/R/make/shlib.mk:6: recipe for target 'mzR.so' failed
make: *** [mzR.so] Error 1
```
> It did compile with 5.2.x (from devtoolset-4) and worked fine.
> I'm hoping you guys could confirm it is purely compiler problem? Or point me(not a real programmer) a way to troubleshoot it properly?

Any idea?

**Comment by sneumann** [comment]
Hi,  We need more information, the error message looks truncated. This is the linking Step, and if the *.o are missing,
The compile steps before have failed. But then it should not have reached the linking in first place. And yes, of course we want to help the original poster.
Yours Steffen

---
I blame Android for the brevity and typos

**Comment by lejeczek** [comment]
actually, mzR does not compile at all on eg. Centos 7.x in R-core-3.3.2-2.el7.x86_64.
I've been now trying vanilla-plain distro's R and mzR fails the same exact way.
I attached a log but I'm worried that might not be good enough.
[mzR.compile-fails.txt](https://github.com/sneumann/mzR/files/668894/mzR.compile-fails.txt)

**Comment by sneumann** [comment]
Hi, The log was perfectly fine. What surprised me was the message

Bioconductor version 3.4 (BiocInstaller 1.24.0), ?biocLite for help

Towards the end. Looks like bioclite
Was restarted?  My suspicion is that it is your R instalation. Can you try R CMD INSTALL mzr-.....tar.gz<http://tar.gz> manually?
Yours Steffen
---
I blame Android for the brevity and typos

**Comment by sneumann** [comment]
One more thing, what is that missing sos package on startup? Does it work of you install as a different user, or remove any /home/user/.R?

---
I blame Android for the brevity and typos

**Comment by lejeczek** [comment]
it is probably because I load a few bits at startup time, but I also tried without.
I do it all as root, in my .Rprofile:

#options(BioC_mirror = "http://mirrors.ebi.ac.uk/bioconductor/")
#options(repos = structure(c (CRAN="http://mirrors.ebi.ac.uk/CRAN/","http://cran.ma.imperial.ac.uk/")))
#options(defaultPackages=c(getOption("defaultPackages"), "utils", "BiocInstaller", "sos"))
Sys.setenv(MAKEFLAGS = "-j11")

and yes I did CMD INSTALL -fails the same.

**Comment by sneumann** [comment]
Is that on a docker container I could try?

---
I blame Android for the brevity and typos

**Comment by lejeczek** [comment]
ok, MAKEFLAGS = "-j15" (or any value other than 1 I'd imagine?) beaks your package build (at least on my all different Centoses). I hope you can fix it? It would be a shame otherwise.

**Comment by sneumann** [comment]
Hi, I just saw this. 
I can't think of anything we got wrong, I am open to suggestions:

In line 118 we define what object files make up our package shared lib mzR.so:
https://github.com/sneumann/mzR/blob/master/src/Makevars#L118

So all objects will be built in parallel, and the Makefile logic for linking 
that into a *.so is in the R system Makefile parts. I saw from your logs 
that only a part of the *.o files was missing, could it be a filesystem 
issue, where some process claimed to have written file.o, 
and the linker process was unable to find it on disk ? Akin 
to write-back caching issue ? Yours, Steffen

**Comment by sneumann** [comment]
Please re-open if persists
