### ISSUE TITLE
Note: mzR sticker

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#82]
I've created an `mzR` sticker at the https://github.com/jotsetung/BioC-stickers repo. Let me know if you'd like me to change something or if you're OK with it.

**Comment by sneumann** [comment]
cool! A nice Grundlinie for the package name would be cool,
looks nicer if several packages are shown (like in the link above)

**Comment by jotsetung** [comment]
What exactly do you mean with Grundlinie? Draw a line below the package name (underline the name)?
I'll also make a version with dark font - just to compare.

**Comment by sneumann** [comment]
I meant the vertical alignment of the texts:

![image](https://cloud.githubusercontent.com/assets/195385/23676403/e755ebc8-037c-11e7-88bb-a955c16e4ba1.png)

**Comment by jotsetung** [comment]
Agreed.

**Comment by jotsetung** [comment]
See https://github.com/jotsetung/BioC-stickers/issues/8 for more discussions on the `mzR` sticker and a dark alternative version.
