### ISSUE TITLE
Unable to install mzR on macOS

### ISSUE THREAD

**Issue by jotsetung** [sneumann/mzR#85]
I'm failing to install `mzR` from source on macOS:
```
installing to /Users/jo/R/R-3.4-devel-BioC3.5-devel/lib/R/library/mzR/libs/x86_64
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘mzR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/jo/R/R-3.4-devel-BioC3.5-devel/lib/R/library/mzR/libs/x86_64/mzR.so':
  dlopen(/Users/jo/R/R-3.4-devel-BioC3.5-devel/lib/R/library/mzR/libs/x86_64/mzR.so, 6): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/jo/R/R-3.4-devel-BioC3.5-devel/lib/R/library/mzR/libs/x86_64/mzR.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/jo/R/R-3.4-devel-BioC3.5-devel/lib/R/library/mzR’
Error: Command failed (1)
```
I tried to install the version on Bioconductor and the one from github but get the same error on both.

**Comment by jotsetung** [comment]
I'm installing it to R devel (2017-03-08 r72321) and R devel (2017-01-19 r72014) and various version of `mzR`:
+ 2.9.7 fails for both R versions
+ 2.9.6 fails for both R versions.

Since I have version 2.9.6 installed on the older R (2017-01-19) I start wondering whether it's something related to my system.

**Comment by jotsetung** [comment]
I don't really understand the error, because `libnetcdf.11.dylib` is located in */usr/local/lib* and *should* be found by R/mzR. Strange.

**Comment by jotsetung** [comment]
OK, so it's not my recent changes to the system. Get the same failure on a stock macos 10.12.3. Will investigate further.

**Comment by jotsetung** [comment]
OK, i've got:
+ netcdf-4.4.1.1_4
+ hdf5-1.10.0-patch1
and `R CMD INSTALL mzR` builds and compiles the package but it can not load it:
```
installing to /Users/jo/R/R-3.4-devel/lib/R/library/mzR/libs/x86_64
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘mzR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/jo/R/R-3.4-devel/lib/R/library/mzR/libs/x86_64/mzR.so':
  dlopen(/Users/jo/R/R-3.4-devel/lib/R/library/mzR/libs/x86_64/mzR.so, 6): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/jo/R/R-3.4-devel/lib/R/library/mzR/libs/x86_64/mzR.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
```
I will investigate further, but if anybody sees something obvious or has a suggestion I would be grateful.

**Comment by jotsetung** [comment]
@sneumann @lgatto , which version of boost are you using on your systems? I have 1.63.0

**Comment by sneumann** [comment]
I have 1.5x, and in fact mzR should use the bundled headers inside mzR

---
I blame Android for the brevity and typos

**Comment by lgatto** [comment]
I have `1.54` and `1.55`. In `checkoutpwiz.sh`, we seem to fetch `1.58`.

**Comment by jotsetung** [comment]
I uninstalled boost from my system - get the same error. yes, it uses the bundled boost - wasn't aware of that. Next I'll try with a pre-compiled R.

**Comment by jotsetung** [comment]
Same error, also with the R-devel from CRAN. Will try an older macos version (< 10.12.3).

**Comment by jotsetung** [comment]
Fixed it: seems to be related to the `netcdf` that is distributed *via* `homebrew`. To fix:
+ Uninstall the `netcdf` from `homebrew`: `brew uninstall netcdf`.
+ Download the `netcdf` (version 4.4.1.1) source, compile and install (just plain `configure`, `make`, `make install`).

Works now. Guess there might be something broken with the `homebrew` `netcdf`.

**Comment by woodruffw** [comment]
Hi there, homebrew maintainer here.

We had a bug in some of our binary relocation code, and it looks like it found its way down to you. You *should* be able to fix the problem with our version of `netcdf` by running `brew reinstall netcdf`, which will correctly relocate the dynamic libraries.

Sorry for all the trouble, and please let me know if it works!

**Comment by lgatto** [comment]
Thank you for following up, @woodruffw.

**Comment by jotsetung** [comment]
Thanks @woodruffw . Works now!

That's the netcdf I've got:
```
jobook:~ jo$ brew info netcdf
homebrew/science/netcdf: stable 4.4.1.1 (bottled)
Libraries and data formats for array-oriented scientific data
http://www.unidata.ucar.edu/software/netcdf
/usr/local/Cellar/netcdf/4.4.1.1_4 (66 files, 2.3MB) *
  Poured from bottle on 2017-04-17 at 08:24:08
From: https://github.com/Homebrew/homebrew-science/blob/master/netcdf.rb
==> Dependencies
Build: cmake ✔
Required: hdf5 ✔
==> Requirements
Optional: fortran ✔
==> Options
--with-fortran
	Build with fortran support
--without-test
	Disable checks (not recommended)
```

**Comment by woodruffw** [comment]
Glad to hear it!

**Comment by LianglRen** [comment]
Another issue, I tired to install package"DEP" which depends on mzR and netcdf, it reported same error like jorainer's, however neither reinstalling of netcdf and mzR or compiling from the source fixed this, finally it turned to be 'Rcpp', remove and reinstall of the Rcpp package fixed the error.
