### ISSUE TITLE
mzR has been built against a different Rcpp version (0.12.8)

### ISSUE THREAD

**Issue by Muiiki** [sneumann/mzR#93]
Warning message:
In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.8)
than is installed on your system (0.12.10). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.

**Comment by lgatto** [comment]
Sorry, missed this one. This is a warning that can be ignored, and probably disappeared now as we have pushed changes and mzR got built against a newer Rcpp on Windows and Mac.
