### ISSUE TITLE
/bin/bash: nc-config: command not found

### ISSUE THREAD

**Issue by OnlyBelter** [sneumann/mzR#99]
When I insall mzR by `install.packages('/home/beltet/Downloads/mzR_2.10.0.tar.gz', repos=NULL, type='source')`, I got this prompt message `/bin/bash: nc-config: command not found` many times. What does it mean?

**Comment by sneumann** [comment]
Hi, there is a binary `/usr/bin/nc-config` that is part of Linux package `libnetcdf-dev`.
During compilation of mzR this can point to the header files and include files:
```
nc-config --cflags
-I/usr/include -I/usr/include/hdf5/serial
```
if that file is not present, mzR omits the include paths, hoping/expecting they are available. 
So the `command not found` is just a cosmetic issue if the rest of the compilation succeeds.
Yours, Steffen
